const sampleProducts = [
  // 1. Rice, Atta & Dal
  {
    title: "Basmati Rice Premium",
    price: 150,
    discountPrice: 135,
    imageUrl: "https://cdn.grofers.com/da/cms-assets/cms/product/338f2cd4-9cb3-408b-9517-0b51d0783f1c.jpg?ts=1738400186",
    quantity: "5 kg",
    sellerName: "Organic Farms",
    sellerAddress: "123 Farm Road, Punjab, India",
    manufactureDate: new Date("2025-01-01"),
    expiryDate: new Date("2026-01-01"),
    disclaimer: "Store in a cool, dry place.",
    description: "Premium quality basmati rice, aromatic and long-grained.",
    createdBy: "admin1",
    categorySlug: "rice-atta-dal",
    createdAt: new Date("2025-06-01")
  },
  {
    title: "Toor Dal",
    price: 120,
    discountPrice: 110,
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS5ObLLCv7g2Of6BCgu1yyGUFkqQUHG9-Dm6Q&s",
    quantity: "1 kg",
    sellerName: "Pure Grains",
    sellerAddress: "456 Grain Market, Gujarat, India",
    manufactureDate: new Date("2025-02-01"),
    expiryDate: new Date("2026-02-01"),
    disclaimer: "Check for impurities before use.",
    description: "High-quality toor dal, ideal for daily cooking.",
    createdBy: "admin2",
    categorySlug: "rice-atta-dal",
    createdAt: new Date("2025-06-02")
  },
  {
    title: "Sona Masoori Rice",
    price: 140,
    discountPrice: 125,
    imageUrl: "https://www.indiagatefoods.com/wp-content/uploads/2025/05/sona-masoori-rice-10k-front.png",
    quantity: "10 kg",
    sellerName: "Grain World",
    sellerAddress: "101 Rice Market, Andhra Pradesh, India",
    manufactureDate: new Date("2025-03-01"),
    expiryDate: new Date("2026-03-01"),
    disclaimer: "Store in a dry place.",
    description: "High-quality Sona Masoori rice, ideal for daily meals.",
    createdBy: "admin3",
    categorySlug: "rice-atta-dal",
    createdAt: new Date("2025-06-25")
  },
  {
    title: "Whole Wheat Atta",
    price: 220,
    discountPrice: 200,
    imageUrl: "https://m.media-amazon.com/images/I/91nBm7ilp9L.jpg",
    quantity: "5 kg",
    sellerName: "Grain World",
    sellerAddress: "101 Rice Market, Andhra Pradesh, India",
    manufactureDate: new Date("2025-04-01"),
    expiryDate: new Date("2026-04-01"),
    disclaimer: "Check for impurities before use.",
    description: "Nutritious whole wheat atta for soft rotis.",
    createdBy: "admin4",
    categorySlug: "rice-atta-dal",
    createdAt: new Date("2025-06-26")
  },
  {
    title: "Moong Dal",
    price: 90,
    discountPrice: 80,
    imageUrl: "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcSdz2p4LUiwQ_MDNLrkPj9bJjcVeRWS9njU6Q0DUsYb423E9IfcsiO4zb2StXlYgM33zrlLLjBe55Rel0y22pxWqYsii0KNWAykLmh4Hcu60lDRMVwXS-IAHFBhdx5Qikm-fcixHg&usqp=CAc",
    quantity: "500 g",
    sellerName: "Pure Pulses",
    sellerAddress: "202 Pulse Lane, Rajasthan, India",
    manufactureDate: new Date("2025-05-01"),
    expiryDate: new Date("2026-05-01"),
    disclaimer: "Store in an airtight container.",
    description: "Premium moong dal for soups and curries.",
    createdBy: "admin3",
    categorySlug: "rice-atta-dal",
    createdAt: new Date("2025-06-27")
  },
  {
    title: "Chana Dal",
    price: 110,
    discountPrice: 100,
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT97c3pu241Bvy8oti6sfpxUC9jF_d_w0EWGw&s",
    quantity: "1 kg",
    sellerName: "Pure Pulses",
    sellerAddress: "202 Pulse Lane, Rajasthan, India",
    manufactureDate: new Date("2025-05-15"),
    expiryDate: new Date("2026-05-15"),
    disclaimer: "Soak before cooking.",
    description: "High-protein chana dal for traditional dishes.",
    createdBy: "admin4",
    categorySlug: "rice-atta-dal",
    createdAt: new Date("2025-06-28")
  },
  {
    title: "Brown Rice",
    price: 180,
    discountPrice: 160,
    imageUrl: "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcRWk9xgqYJYczow5XCQY7OgGw5Q7t20JHbY-Ng2TUXIFIZQ037kiBOLlflXbdWAxcBNx_caMK9Ei36DfC6H59zPKHOp0YCCkcyZNp3pfg_GlB0S1nriRaXhyPJW4uHGvrGJV1Oivw&usqp=CAc",
    quantity: "5 kg",
    sellerName: "Grain World",
    sellerAddress: "101 Rice Market, Andhra Pradesh, India",
    manufactureDate: new Date("2025-06-01"),
    expiryDate: new Date("2026-06-01"),
    disclaimer: "Store in a cool, dry place.",
    description: "Healthy brown rice, rich in fiber.",
    createdBy: "admin3",
    categorySlug: "rice-atta-dal",
    createdAt: new Date("2025-06-29")
  },

  // 2. Oil & Ghee
  {
    title: "Sunflower Oil",
    price: 200,
    discountPrice: 180,
    imageUrl: "https://images-cdn.ubuy.co.in/670c8b9292874f79231c0e67-pure-sunflower-oil-packed-in-2-liter-jar.jpg",
    quantity: "1 litre",
    sellerName: "Healthy Oils",
    sellerAddress: "789 Oil Mill, Maharashtra, India",
    manufactureDate: new Date("2025-03-01"),
    expiryDate: new Date("2026-03-01"),
    disclaimer: "Keep away from direct sunlight.",
    description: "Pure sunflower oil for healthy cooking.",
    createdBy: "admin1",
    categorySlug: "oil-ghee",
    createdAt: new Date("2025-06-03")
  },
  {
    title: "Desi Ghee",
    price: 600,
    discountPrice: 550,
    imageUrl: "https://m.media-amazon.com/images/I/315l7daRruL._SX300_SY300_QL70_FMwebp_.jpg",
    quantity: "500 ml",
    sellerName: "Pure Dairy",
    sellerAddress: "101 Dairy Lane, Haryana, India",
    manufactureDate: new Date("2025-04-01"),
    expiryDate: new Date("2026-04-01"),
    disclaimer: "Store in an airtight container.",
    description: "Rich and aromatic desi ghee made from cow milk.",
    createdBy: "admin2",
    categorySlug: "oil-ghee",
    createdAt: new Date("2025-06-04")
  },
  {
    title: "Mustard Oil",
    price: 190,
    discountPrice: 170,
    imageUrl: "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcROPDo4ALjm90Uv2Ntgsc_ApA81HWY-U3qz0qucG3gKcld1Iqv_Ody-18XDBVyIntYqpL4hUcDNHn0YnjIh2whIwthPiY0nPyJ3y879lVVIRtPUXoZ1Xek5YuWsqhd-iQgN1RulyQ&usqp=CAc",
    quantity: "1 litre",
    sellerName: "Pure Oils",
    sellerAddress: "303 Oil Street, West Bengal, India",
    manufactureDate: new Date("2025-02-15"),
    expiryDate: new Date("2026-02-15"),
    disclaimer: "Use in moderation.",
    description: "Pure mustard oil for authentic Indian cooking.",
    createdBy: "admin4",
    categorySlug: "oil-ghee",
    createdAt: new Date("2025-06-25")
  },
  {
    title: "Cow Ghee",
    price: 650,
    discountPrice: 600,
    imageUrl: "https://m.media-amazon.com/images/I/315l7daRruL._SX300_SY300_QL70_FMwebp_.jpg",
    quantity: "1 kg",
    sellerName: "Dairy Pure",
    sellerAddress: "404 Dairy Road, Gujarat, India",
    manufactureDate: new Date("2025-03-15"),
    expiryDate: new Date("2026-03-15"),
    disclaimer: "Store in a cool place.",
    description: "Pure cow ghee for rich flavor and aroma.",
    createdBy: "admin3",
    categorySlug: "oil-ghee",
    createdAt: new Date("2025-06-26")
  },
  {
    title: "Olive Oil",
    price: 500,
    discountPrice: 450,
    imageUrl: "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcTozSNEYNWCU62YymK0f8l_CJC2P6mLGXODyyZybiueVQFA2tF_9x3ndq3ielPCa7IZKV7n1D8JzjCrOdEKjUpxHXwvcGi94vCZMIuvQ2ygLbvA6Wrw9t52aTQmO1JPByaY2mjZgVg&usqp=CAc",
    quantity: "500 ml",
    sellerName: "Pure Oils",
    sellerAddress: "303 Oil Street, West Bengal, India",
    manufactureDate: new Date("2025-04-15"),
    expiryDate: new Date("2026-04-15"),
    disclaimer: "Keep away from heat.",
    description: "Extra virgin olive oil for healthy cooking.",
    createdBy: "admin4",
    categorySlug: "oil-ghee",
    createdAt: new Date("2025-06-27")
  },
  {
    title: "Coconut Oil",
    price: 250,
    discountPrice: 225,
    imageUrl: "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcQgMZY-3QcB1Fd5OPk9t83g1YeTuBMPjZUhxez6KEUEcBJlEWCHNb3a7bqm9eo_I_L0I0AmonK8TePF_TUDTVs9o6u5W-UdEFS71KQ6v8J-s-z47b7M7AXcjBx-usawERDFxjPb1UtDaA&usqp=CAc",
    quantity: "1 litre",
    sellerName: "Pure Oils",
    sellerAddress: "303 Oil Street, West Bengal, India",
    manufactureDate: new Date("2025-05-01"),
    expiryDate: new Date("2026-05-01"),
    disclaimer: "Store in a dry place.",
    description: "Pure coconut oil for cooking and hair care.",
    createdBy: "admin3",
    categorySlug: "oil-ghee",
    createdAt: new Date("2025-06-28")
  },
  {
    title: "Buffalo Ghee",
    price: 700,
    discountPrice: 650,
    imageUrl: "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcR21Xto30hz5N7oSuN1VetraZvmspnVSsgLXjV698QE9Hp42HCOutPfZgXRmeCw8ZteJ3LZvPk0xpGpyg9hbpiVF3xqRtrz45gkqWBmMI6m",
    quantity: "500 ml",
    sellerName: "Dairy Pure",
    sellerAddress: "404 Dairy Road, Gujarat, India",
    manufactureDate: new Date("2025-06-01"),
    expiryDate: new Date("2026-06-01"),
    disclaimer: "Store in an airtight container.",
    description: "Rich buffalo ghee for traditional recipes.",
    createdBy: "admin4",
    categorySlug: "oil-ghee",
    createdAt: new Date("2025-06-29")
  },

  // 3. Masala & Spices
  {
    title: "Garam Masala",
    price: 80,
    discountPrice: 70,
    imageUrl: "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcTnxqQFin5OwLyxVzc5g7LL6gKlyw-cTG1OlA9O9ReppZm4LtFPOpjm11GRqzxHlLQ3m4Z-FXAd9mT78zZ6Cuy1_gyNu0WykXTY-XT3NMWAwHvngOmC9OJv",
    quantity: "100 g",
    sellerName: "Spice Hub",
    sellerAddress: "321 Spice Market, Delhi, India",
    manufactureDate: new Date("2025-05-01"),
    expiryDate: new Date("2026-05-01"),
    disclaimer: "Store in a cool, dry place.",
    description: "Authentic blend of Indian spices for flavorful dishes.",
    createdBy: "admin1",
    categorySlug: "masala-spices",
    createdAt: new Date("2025-06-05")
  },
  {
    title: "Turmeric Powder",
    price: 50,
    discountPrice: 45,
    imageUrl: "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcRiSCP0T_oT9SKKCDOP_eRrbXYrNe3785gXBMCyiWfMUH6fXPYLVLtLaKT4eF0d4eW8IcYZnPUi31gbS7yWjOlKBWG4j6qa-j71zfT7_v5gRhWGi1SC1QpU",
    quantity: "200 g",
    sellerName: "Spice Hub",
    sellerAddress: "321 Spice Market, Delhi, India",
    manufactureDate: new Date("2025-05-15"),
    expiryDate: new Date("2026-05-15"),
    disclaimer: "Store in a cool, dry place.",
    description: "Pure turmeric powder with natural color and aroma.",
    createdBy: "admin2",
    categorySlug: "masala-spices",
    createdAt: new Date("2025-06-06")
  },
  {
    title: "Coriander Powder",
    price: 60,
    discountPrice: 50,
    imageUrl: "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcS0gFjK-6hu8c6e3Z4936fss6Yuz0HkwOnVFK3Tq0leOJj8hAC_Zj2cRLmKgMtiX_QVeTr9SZeND4R51t1sD0gGCAQOEqEMHrlwaDSSUlkdd1vf1-rlQOKmrw",
    quantity: "200 g",
    sellerName: "Spice World",
    sellerAddress: "505 Spice Market, Mumbai, India",
    manufactureDate: new Date("2025-03-01"),
    expiryDate: new Date("2026-03-01"),
    disclaimer: "Store in a cool, dry place.",
    description: "Freshly ground coriander powder for curries.",
    createdBy: "admin3",
    categorySlug: "masala-spices",
    createdAt: new Date("2025-06-25")
  },
  {
    title: "Red Chilli Powder",
    price: 70,
    discountPrice: 60,
    imageUrl: "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcQKY6kFiWGtit3VyM7IItMHhVbkILNQTTbu7GLW093QjmOyCjEInFMW6cXR5t7Wq2w7_XZ88XxfTk7Yvocnzis8QgoKrU3shayRIER9vcQ7-j9O8Y6Egy7h",
    quantity: "100 g",
    sellerName: "Spice World",
    sellerAddress: "505 Spice Market, Mumbai, India",
    manufactureDate: new Date("2025-04-01"),
    expiryDate: new Date("2026-04-01"),
    disclaimer: "Handle with care.",
    description: "Spicy red chilli powder for bold flavors.",
    createdBy: "admin4",
    categorySlug: "masala-spices",
    createdAt: new Date("2025-06-26")
  },
  {
    title: "Cumin Seeds",
    price: 80,
    discountPrice: 70,
    imageUrl: "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcRlbz185iYcXRQm-C5G_144GQNhkvn6UZCFYU5d3Xv-kS2lWfBoVy_lLTYwk8zjTO6Z3g6Uni5a6K4R1todftNIhONXzCmtwy5lLAPTtdc7Hxn-ACaqR2Si",
    quantity: "100 g",
    sellerName: "Spice World",
    sellerAddress: "505 Spice Market, Mumbai, India",
    manufactureDate: new Date("2025-05-01"),
    expiryDate: new Date("2026-05-01"),
    disclaimer: "Store in an airtight container.",
    description: "Aromatic cumin seeds for seasoning.",
    createdBy: "admin3",
    categorySlug: "masala-spices",
    createdAt: new Date("2025-06-27")
  },
  {
    title: "Black Pepper",
    price: 100,
    discountPrice: 90,
    imageUrl: "https://www.bulksupplements.com/cdn/shop/files/Black-Pepper-Extract-Powder-50g-Main-Image-V002.jpg?v=1739573955&width=600",
    quantity: "100 g",
    sellerName: "Spice World",
    sellerAddress: "505 Spice Market, Mumbai, India",
    manufactureDate: new Date("2025-05-15"),
    expiryDate: new Date("2026-05-15"),
    disclaimer: "Store in a dry place.",
    description: "Whole black pepper for intense flavor.",
    createdBy: "admin4",
    categorySlug: "masala-spices",
    createdAt: new Date("2025-06-28")
  },
  {
    title: "Chicken Masala",
    price: 90,
    discountPrice: 80,
    imageUrl: "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcSfga05A9S00dZWkXlnMA6NgKYQSWHOz94M_8ixnsxlmQlDRmlkYHVFkxLsxqZPpRJcU6fLWdpTrx4oZB7GuMWfIRRYJT-51x78HNLBMZDYCLuAg2Rvdv6KCrO-AYkbP2uE8jyGmss&usqp=CAc",
    quantity: "100 g",
    sellerName: "Spice World",
    sellerAddress: "505 Spice Market, Mumbai, India",
    manufactureDate: new Date("2025-06-01"),
    expiryDate: new Date("2026-06-01"),
    disclaimer: "Store in a cool place.",
    description: "Special blend for delicious chicken dishes.",
    createdBy: "admin3",
    categorySlug: "masala-spices",
    createdAt: new Date("2025-06-29")
  },

  // 4. Festive & Gifting
  {
    title: "Diwali Gift Hamper",
    price: 1000,
    discountPrice: 900,
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSCGZotenNrJpkD6Re1SoOfAellGThmJvIUfw&s",
    quantity: "1 pack",
    sellerName: "Festive Gifts",
    sellerAddress: "654 Gift Street, Mumbai, India",
    manufactureDate: new Date("2025-06-01"),
    expiryDate: new Date("2026-06-01"),
    disclaimer: "Contains dry fruits and sweets.",
    description: "Premium Diwali gift hamper with sweets and dry fruits.",
    createdBy: "admin1",
    categorySlug: "festive-gifting",
    createdAt: new Date("2025-06-07")
  },
  {
    title: "Rakhi Gift Box",
    price: 500,
    discountPrice: 450,
    imageUrl: "https://www.fnp.com//images/pr/l/v20240709151713/kundan-rakhi-n-siblings-treasure-box_1.jpg",
    quantity: "1 pack",
    sellerName: "Festive Gifts",
    sellerAddress: "654 Gift Street, Mumbai, India",
    manufactureDate: new Date("2025-06-10"),
    expiryDate: new Date("2026-06-10"),
    disclaimer: "Contains chocolates and rakhi.",
    description: "Beautiful Rakhi gift box with chocolates and a rakhi.",
    createdBy: "admin2",
    categorySlug: "festive-gifting",
    createdAt: new Date("2025-06-08")
  },
  {
    title: "Holi Gift Pack",
    price: 800,
    discountPrice: 720,
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTvg2ml4z5TkK7b4jfimhYSKhzn2y65JF3yTQ&s",
    quantity: "1 pack",
    sellerName: "Gift Joy",
    sellerAddress: "606 Gift Avenue, Delhi, India",
    manufactureDate: new Date("2025-02-01"),
    expiryDate: new Date("2026-02-01"),
    disclaimer: "Contains sweets and colors.",
    description: "Colorful Holi gift pack with sweets and gulal.",
    createdBy: "admin4",
    categorySlug: "festive-gifting",
    createdAt: new Date("2025-06-25")
  },
  {
    title: "Eid Gift Hamper",
    price: 1200,
    discountPrice: 1080,
    imageUrl: "https://m.media-amazon.com/images/I/91Q+CPW2Z-L.jpg",
    quantity: "1 pack",
    sellerName: "Gift Joy",
    sellerAddress: "606 Gift Avenue, Delhi, India",
    manufactureDate: new Date("2025-03-01"),
    expiryDate: new Date("2026-03-01"),
    disclaimer: "Contains dry fruits and sweets.",
    description: "Luxurious Eid hamper with dry fruits and sweets.",
    createdBy: "admin3",
    categorySlug: "festive-gifting",
    createdAt: new Date("2025-06-26")
  },
  {
    title: "Christmas Gift Box",
    price: 900,
    discountPrice: 810,
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRjOu_C6nyzOG0CDKZm-zaNXJdzl0ORaSia7g&s",
    quantity: "1 pack",
    sellerName: "Gift Joy",
    sellerAddress: "606 Gift Avenue, Delhi, India",
    manufactureDate: new Date("2025-04-01"),
    expiryDate: new Date("2026-04-01"),
    disclaimer: "Contains chocolates and cookies.",
    description: "Festive Christmas gift box with treats.",
    createdBy: "admin4",
    categorySlug: "festive-gifting",
    createdAt: new Date("2025-06-27")
  },
  {
    title: "Wedding Gift Pack",
    price: 1500,
    discountPrice: 1350,
    imageUrl: "https://brownliving.in/cdn/shop/files/sustainable-conscious-couple-gift-set-sustainable-wedding-gift-for-bride-groom-by-bare-necessities-at-brownliving-159560.jpg?v=1745907648",
    quantity: "1 pack",
    sellerName: "Gift Joy",
    sellerAddress: "606 Gift Avenue, Delhi, India",
    manufactureDate: new Date("2025-05-01"),
    expiryDate: new Date("2026-05-01"),
    disclaimer: "Contains sweets and dry fruits.",
    description: "Elegant wedding gift pack with premium items.",
    createdBy: "admin3",
    categorySlug: "festive-gifting",
    createdAt: new Date("2025-06-28")
  },
  {
    title: "New Year Gift Hamper",
    price: 1000,
    discountPrice: 900,
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR9KhT_hnrLQmqDFKdF8vO5OmIwyqVuX2gdKA&s",
    quantity: "1 pack",
    sellerName: "Gift Joy",
    sellerAddress: "606 Gift Avenue, Delhi, India",
    manufactureDate: new Date("2025-06-01"),
    expiryDate: new Date("2026-06-01"),
    disclaimer: "Contains chocolates and snacks.",
    description: "Celebratory New Year hamper with treats.",
    createdBy: "admin4",
    categorySlug: "festive-gifting",
    createdAt: new Date("2025-06-29")
  },

  // 5. Beverages
  {
    title: "Green Tea",
    price: 250,
    discountPrice: 225,
    imageUrl: "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcQcHICjIxYGU0Vq7y8Uq_d813qVlgQqcoANJWNj1p4z4NOcfc8xhUmGvZ_TwYpKYEqCnqOdW1xS0FR688BiZ1HePt7kBfclr7bK6j0tGTxpegA1P48j4yifwrod8zbFiWMXeBGyrA&usqp=CAc",
    quantity: "100 g",
    sellerName: "Tea Gardens",
    sellerAddress: "987 Tea Estate, Assam, India",
    manufactureDate: new Date("2025-01-15"),
    expiryDate: new Date("2026-01-15"),
    disclaimer: "Store in an airtight container.",
    description: "Refreshing green tea from Assam tea gardens.",
    createdBy: "admin1",
    categorySlug: "beverages",
    createdAt: new Date("2025-06-09")
  },
  {
    title: "Instant Coffee",
    price: 300,
    discountPrice: 270,
    imageUrl: "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcT_0YGDOX3N2hfX4wSTpeK5kSlKVbZ-4JP-ZOsRKC01JiNUSBd-1Go60Y4jfSvmmnp7eaiwx6-9aWrJpD9sv9yYoMzEKuo6H8kGU5mTo1Mey_XyT6w850rX3oi62atD_iK5TcGQjmw&usqp=CAc",
    quantity: "200 g",
    sellerName: "Coffee Co",
    sellerAddress: "111 Coffee Lane, Karnataka, India",
    manufactureDate: new Date("2025-02-15"),
    expiryDate: new Date("2026-02-15"),
    disclaimer: "Store in a cool, dry place.",
    description: "Rich instant coffee for a quick caffeine fix.",
    createdBy: "admin2",
    categorySlug: "beverages",
    createdAt: new Date("2025-06-10")
  },
  {
    title: "Masala Tea",
    price: 200,
    discountPrice: 180,
    imageUrl: "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcSTKH9-6lxFI45RcwWMJtmcXCjxGoTUOs4t7B71aPzbQuE39YkBzTTNBw83XvIEnxTD5WlaflToQ6_pfk9J5kgkEhkKciNab0_mPH0-DMMDZjp_Ydk2kgBhwqUBufZAkhz4AOIxUQ&usqp=CAc",
    quantity: "250 g",
    sellerName: "Tea Bliss",
    sellerAddress: "707 Tea Estate, Darjeeling, India",
    manufactureDate: new Date("2025-03-01"),
    expiryDate: new Date("2026-03-01"),
    disclaimer: "Store in a dry place.",
    description: "Aromatic masala tea for a refreshing start.",
    createdBy: "admin3",
    categorySlug: "beverages",
    createdAt: new Date("2025-06-25")
  },
  {
    title: "Cold Coffee Mix",
    price: 250,
    discountPrice: 225,
    imageUrl: "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcTEKBZ03legbSeAa3aaIGNkSytaX5Ii5679NEa_RJ1slndxaFnxYrHmJRjlsrjxt5IY6oj3NBKlHerIoti3chHw4bxKzyzbvJ-_KUxaB3-QCrdSfABYaL9yTKUhv_Pm12sV9pijFg&usqp=CAc",
    quantity: "200 g",
    sellerName: "Coffee Delight",
    sellerAddress: "808 Coffee Lane, Coorg, India",
    manufactureDate: new Date("2025-04-01"),
    expiryDate: new Date("2026-04-01"),
    disclaimer: "Mix with cold milk.",
    description: "Instant cold coffee mix for a quick beverage.",
    createdBy: "admin4",
    categorySlug: "beverages",
    createdAt: new Date("2025-06-26")
  },
  {
    title: "Lemon Tea",
    price: 180,
    discountPrice: 160,
    imageUrl: "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcQcHICjIxYGU0Vq7y8Uq_d813qVlgQqcoANJWNj1p4z4NOcfc8xhUmGvZ_TwYpKYEqCnqOdW1xS0FR688BiZ1HePt7kBfclr7bK6j0tGTxpegA1P48j4yifwrod8zbFiWMXeBGyrA&usqp=CAc",
    quantity: "100 g",
    sellerName: "Tea Bliss",
    sellerAddress: "707 Tea Estate, Darjeeling, India",
    manufactureDate: new Date("2025-05-01"),
    expiryDate: new Date("2026-05-01"),
    disclaimer: "Store in an airtight container.",
    description: "Zesty lemon tea for a refreshing drink.",
    createdBy: "admin3",
    categorySlug: "beverages",
    createdAt: new Date("2025-06-27")
  },
  {
    title: "Herbal Tea",
    price: 220,
    discountPrice: 200,
    imageUrl: "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcT5fZR_Zp-Ah9z0KPHc3h_jPcAXpGQ5SdlYxaR7IRt-jLryo60kOPv8r1k2URdXd3Za6ESAEDrSj3qe88z6YxBDGCudXFZUvUNBHphUyYyu_cAOIkzCHTwuQ-_tZVzruyl4oERCx88&usqp=CAc",
    quantity: "100 g",
    sellerName: "Tea Bliss",
    sellerAddress: "707 Tea Estate, Darjeeling, India",
    manufactureDate: new Date("2025-05-15"),
    expiryDate: new Date("2026-05-15"),
    disclaimer: "Consult a doctor if allergic.",
    description: "Calming herbal tea for relaxation.",
    createdBy: "admin4",
    categorySlug: "beverages",
    createdAt: new Date("2025-06-28")
  },
  {
    title: "Filter Coffee",
    price: 300,
    discountPrice: 270,
    imageUrl: "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcT6tlL_BPg3iqgp7Ttzd_5b-JTEGYErGlMHaWEkRm6Wgin_CApdDSBkLZxcBtxWqjDTmYy5I3sVhdHQ5fJpFDlBJARX6AiKvuaDtiN4jC_4x-tu3sS9q70XxIywWHsZ2n4CTZQN18U&usqp=CAc",
    quantity: "250 g",
    sellerName: "Coffee Delight",
    sellerAddress: "808 Coffee Lane, Coorg, India",
    manufactureDate: new Date("2025-06-01"),
    expiryDate: new Date("2026-06-01"),
    disclaimer: "Store in a cool place.",
    description: "Authentic South Indian filter coffee powder.",
    createdBy: "admin3",
    categorySlug: "beverages",
    createdAt: new Date("2025-06-29")
  },

  // 6. Personal Care
  {
    title: "Herbal Shampoo",
    price: 200,
    discountPrice: 180,
    imageUrl: "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcT3T0BcO25Qcw3WBaxF07NwqlKnx2bldHpK6IC9iQE36XCMEqfHRsdp05gbeFoMBF5MXZ657Zo3n9ZdrZ9Tfj2-qX8mZUclmc_erayUnDyZi9BI3dBcRPnXG1FOTWQoHKGoponxO-o&usqp=CAc",
    quantity: "200 ml",
    sellerName: "Natural Care",
    sellerAddress: "222 Wellness Road, Kerala, India",
    manufactureDate: new Date("2025-03-10"),
    expiryDate: new Date("2026-03-10"),
    disclaimer: "For external use only.",
    description: "Gentle herbal shampoo for healthy hair.",
    createdBy: "admin1",
    categorySlug: "personal-care",
    createdAt: new Date("2025-06-11")
  },
  {
    title: "Face Wash",
    price: 150,
    discountPrice: 135,
    imageUrl: "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcSjERhvjDye0bTz1MzswDszZbt_G3s_YMfRJnToMU6mq1gK3hj1fFJBj3E2ls5W7V-QPcRhaG5x59pkxY8L3o1VuxZP0pG-Z0WDbFE5PaENHU5M17134PkYDo3akaBaXY33vwtQOg&usqp=CAc",
    quantity: "100 ml",
    sellerName: "Natural Care",
    sellerAddress: "222 Wellness Road, Kerala, India",
    manufactureDate: new Date("2025-04-10"),
    expiryDate: new Date("2026-04-10"),
    disclaimer: "Avoid contact with eyes.",
    description: "Refreshing face wash for clear skin.",
    createdBy: "admin2",
    categorySlug: "personal-care",
    createdAt: new Date("2025-06-12")
  },
  {
    title: "Body Lotion",
    price: 250,
    discountPrice: 225,
    imageUrl: "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcTF7oKYsDFjrm4w8YhkU1AeRmJMEvNpqO33p11M95L2-lmy68wIxc3ieQ5eo0Jr0wdXo3j1qZaKgDdbg22G_U7zKuOoP_RPi6EjmCb-bCwQA0NggIdqZ5vYV4svZQsdZSdQxvWIO50&usqp=CAc",
    quantity: "200 ml",
    sellerName: "Care Plus",
    sellerAddress: "909 Wellness Street, Bangalore, India",
    manufactureDate: new Date("2025-03-01"),
    expiryDate: new Date("2026-03-01"),
    disclaimer: "For external use only.",
    description: "Moisturizing body lotion for soft skin.",
    createdBy: "admin4",
    categorySlug: "personal-care",
    createdAt: new Date("2025-06-25")
  },
  {
    title: "Hair Conditioner",
    price: 200,
    discountPrice: 180,
    imageUrl: "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcQB6h-QMEK4zqOvLY2GdaaP1c-LmsY56-bWzOI_sPfb3VV0onqsKIrclWq95SWDTUSSY-GpKcpL_3EIQzWfe1rOkLuAU5XcM4SfiYkrSn_NjIFdxPZDHXUYcfNbclokGWgb3P0ssw&usqp=CAc",
    quantity: "200 ml",
    sellerName: "Care Plus",
    sellerAddress: "909 Wellness Street, Bangalore, India",
    manufactureDate: new Date("2025-04-01"),
    expiryDate: new Date("2026-04-01"),
    disclaimer: "Avoid contact with eyes.",
    description: "Nourishing conditioner for smooth hair.",
    createdBy: "admin3",
    categorySlug: "personal-care",
    createdAt: new Date("2025-06-26")
  },
  {
    title: "Soap Bar",
    price: 50,
    discountPrice: 45,
    imageUrl: "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcQp76y6WNUMEkheFDjrMudsIU3FvjntG6TxWhFcFgap--oHfAf4R6sb7B_fgOa96GdtWAekcPHIgMeeorzDhrPYqoN2952fYQRZ7Pw_4ZyH5F7dvVDL-S0Wm6VQmyaD2w&usqp=CAc",
    quantity: "100 g",
    sellerName: "Care Plus",
    sellerAddress: "909 Wellness Street, Bangalore, India",
    manufactureDate: new Date("2025-05-01"),
    expiryDate: new Date("2026-05-01"),
    disclaimer: "For external use only.",
    description: "Gentle soap bar for daily cleansing.",
    createdBy: "admin4",
    categorySlug: "personal-care",
    createdAt: new Date("2025-06-27")
  },
  {
    title: "Face Cream",
    price: 300,
    discountPrice: 270,
    imageUrl: "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcQfkNDe0WMdQUmNebjRlE_4aNZ7Tq4_9avPozgCmyKvN_48aaXMW9ht3WO06Zf1QvKINCkvUJfqlrGcYEtu8r3j84in6xl3Z86VwX8hcyDkhkzAPTlyXjTb96KP-cnUZWP3aOMRhg&usqp=CAc",
    quantity: "50 g",
    sellerName: "Care Plus",
    sellerAddress: "909 Wellness Street, Bangalore, India",
    manufactureDate: new Date("2025-05-15"),
    expiryDate: new Date("2026-05-15"),
    disclaimer: "Patch test recommended.",
    description: "Hydrating face cream for glowing skin.",
    createdBy: "admin3",
    categorySlug: "personal-care",
    createdAt: new Date("2025-06-28")
  },
  {
    title: "Hand Wash",
    price: 150,
    discountPrice: 135,
    imageUrl: "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcQ-93o0Cf6V6WPWTzL1Zb1o6-G1ftEDFH145NGgAVmSdQzblum282QfxWW08EMSBkg5TzvCD7wWASyqAS1hUGjyB7RMNhorM9kimUUUEEApZ5bfibk5MapRsQ",
    quantity: "250 ml",
    sellerName: "Care Plus",
    sellerAddress: "909 Wellness Street, Bangalore, India",
    manufactureDate: new Date("2025-06-01"),
    expiryDate: new Date("2026-06-01"),
    disclaimer: "For external use only.",
    description: "Antibacterial hand wash for clean hands.",
    createdBy: "admin4",
    categorySlug: "personal-care",
    createdAt: new Date("2025-06-29")
  },

  // 7. Home Essentials & Cleaning
  {
    title: "Dishwashing Liquid",
    price: 120,
    discountPrice: 100,
    imageUrl: "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcQWXCxXl7GWQvI1kcJg_4Ps3GfxbLsLyODHTbrJOn6gNiRaYlXPPJg2T5snNnBab4SSFIN7Qg53a06TyMC5toimWkGc1xnWZeJiYO7RyVKYNB3GZV0afBu0og",
    quantity: "500 ml",
    sellerName: "Clean Home",
    sellerAddress: "333 Clean Street, Bangalore, India",
    manufactureDate: new Date("2025-05-01"),
    expiryDate: new Date("2026-05-01"),
    disclaimer: "Keep out of reach of children.",
    description: "Effective dishwashing liquid for grease-free dishes.",
    createdBy: "admin1",
    categorySlug: "home-essentials-cleaning",
    createdAt: new Date("2025-06-13")
  },
  {
    title: "Floor Cleaner",
    price: 180,
    discountPrice: 160,
    imageUrl: "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcRj8C21Zqx61B-wn3vDj0Ykcx_ef968PVuWP4QPnw9ckmzxaFQysVymutd-udWayHNZEnfQeekSSVHmgr6XgaL960N-Bro7OJLCYtDbK5j2eT8pkX1lJSvqng",
    quantity: "1 litre",
    sellerName: "Clean Home",
    sellerAddress: "333 Clean Street, Bangalore, India",
    manufactureDate: new Date("2025-05-15"),
    expiryDate: new Date("2026-05-15"),
    disclaimer: "Use gloves while cleaning.",
    description: "Powerful floor cleaner for sparkling floors.",
    createdBy: "admin2",
    categorySlug: "home-essentials-cleaning",
    createdAt: new Date("2025-06-14")
  },
  {
    title: "Laundry Detergent",
    price: 300,
    discountPrice: 270,
    imageUrl: "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcTytkTnFBJ3sSahYwVq1vGCpK76ebpNiG4SVx97iiFDAmmH6vRGB6HOcH6FOpgLde77Kdsde2nQe775ywCa3mSK6LgctpSx",
    quantity: "1 kg",
    sellerName: "Clean Pro",
    sellerAddress: "1010 Clean Avenue, Chennai, India",
    manufactureDate: new Date("2025-03-01"),
    expiryDate: new Date("2026-03-01"),
    disclaimer: "Keep out of reach of children.",
    description: "Powerful laundry detergent for stain removal.",
    createdBy: "admin3",
    categorySlug: "home-essentials-cleaning",
    createdAt: new Date("2025-06-25")
  },
  {
    title: "Glass Cleaner",
    price: 120,
    discountPrice: 100,
    imageUrl: "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcREya2F_QL5BZuO37JEn6SzHq4hFG5er-nLJKWcFWchtYroXnEWPYQKMj1jnE_2ptS9ycoemxDn_yH4bqMEPjm4foXFxX0T9zEyoPU7SifEdQDWIVe-sKdJ2Q",
    quantity: "500 ml",
    sellerName: "Clean Pro",
    sellerAddress: "1010 Clean Avenue, Chennai, India",
    manufactureDate: new Date("2025-04-01"),
    expiryDate: new Date("2026-04-01"),
    disclaimer: "Use in a ventilated area.",
    description: "Streak-free glass cleaner for sparkling surfaces.",
    createdBy: "admin4",
    categorySlug: "home-essentials-cleaning",
    createdAt: new Date("2025-06-26")
  },
  {
    title: "Toilet Cleaner",
    price: 150,
    discountPrice: 135,
    imageUrl: "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcQ_PnleEOuEx1q3siKX9QTGJFn_4bAWNkPmoWWA3h7Qe6pjpdvtXqm1Nyq4V02YSrc6cK76cbiBIIlIrgDpUTDb-1t-GVbCh0KsbhVhkVvN9CXR6c6SVP0pnA",
    quantity: "500 ml",
    sellerName: "Clean Pro",
    sellerAddress: "1010 Clean Avenue, Chennai, India",
    manufactureDate: new Date("2025-05-01"),
    expiryDate: new Date("2026-05-01"),
    disclaimer: "Use gloves while cleaning.",
    description: "Effective toilet cleaner for hygiene.",
    createdBy: "admin3",
    categorySlug: "home-essentials-cleaning",
    createdAt: new Date("2025-06-27")
  },
  {
    title: "Air Freshener",
    price: 200,
    discountPrice: 180,
    imageUrl: "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcRBCxQpDSQJ5rdi42TL3D6CIRVT5ldu-eQ8DNoVO63lI30kOj0xny62Jp6TMyIBptCeajaQX3UBzkoQCUBz5uTe6JGUcnbujZubvRXTUgvf9wD8jKyC0GLPZw",
    quantity: "300 ml",
    sellerName: "Clean Pro",
    sellerAddress: "1010 Clean Avenue, Chennai, India",
    manufactureDate: new Date("2025-05-15"),
    expiryDate: new Date("2026-05-15"),
    disclaimer: "Avoid direct inhalation.",
    description: "Long-lasting air freshener for a pleasant home.",
    createdBy: "admin4",
    categorySlug: "home-essentials-cleaning",
    createdAt: new Date("2025-06-28")
  },
  {
    title: "Dishwashing Powder",
    price: 100,
    discountPrice: 90,
    imageUrl: "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcS4KtTDnOhkl3dsevQvPHzZ-V78kIvuwsRAqcrKZdLmf9_-fy2BP03xmB3UFFD5EYGbQBXk8QqP--ri7eX45-JUxSt8UOEewPc2zSnNEqfKG-tE3u-5WfCx",
    quantity: "500 g",
    sellerName: "Clean Pro",
    sellerAddress: "1010 Clean Avenue, Chennai, India",
    manufactureDate: new Date("2025-06-01"),
    expiryDate: new Date("2026-06-01"),
    disclaimer: "Keep out of reach of children.",
    description: "Effective dishwashing powder for clean utensils.",
    createdBy: "admin3",
    categorySlug: "home-essentials-cleaning",
    createdAt: new Date("2025-06-29")
  },

  // 8. Pooja Essentials
  {
    title: "Agarbatti Pack",
    price: 50,
    discountPrice: 45,
    imageUrl: "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcSHG2mLLuU6dlI-pQz803CoA8m0VIS9DQWlIHHbkx4YSDNQFqUwI2Kf-1Syk5O_u1OvZJJ5cu5pv29Dgi6lREt_BoTzeq3dJYZ3r-gQT8HalewTa-eL7h_SFW0",
    quantity: "100 sticks",
    sellerName: "Divine Store",
    sellerAddress: "444 Temple Road, Varanasi, India",
    manufactureDate: new Date("2025-06-01"),
    expiryDate: new Date("2026-06-01"),
    disclaimer: "Burn safely away from flammable items.",
    description: "Fragrant agarbatti for pooja and meditation.",
    createdBy: "admin1",
    categorySlug: "pooja-essentials",
    createdAt: new Date("2025-06-15")
  },
  {
    title: "Camphor Tablets",
    price: 30,
    discountPrice: 25,
    imageUrl: "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcSVR0v7aH3IBuGXUmcQwZbwENiXUlv_4eM3hwLk9tj5tuHx08_nSgxTbBBiYjSBw5JLFiYbZ2upzlBujobIziIUvDwlWv16um5tVtKkd1j-vcXLzwZ1xOOONQ",
    quantity: "50 g",
    sellerName: "Divine Store",
    sellerAddress: "444 Temple Road, Varanasi, India",
    manufactureDate: new Date("2025-06-10"),
    expiryDate: new Date("2026-06-10"),
    disclaimer: "Store in a cool, dry place.",
    description: "Pure camphor tablets for religious ceremonies.",
    createdBy: "admin2",
    categorySlug: "pooja-essentials",
    createdAt: new Date("2025-06-16")
  },
  {
    title: "Dhoop Sticks",
    price: 60,
    discountPrice: 50,
    imageUrl: "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcSn7rIj7PyG8ozgveomYvwfsPS26nQIzOkWfGaAjtH_dHpRRrtnxdO8RXjvSONCsDWSvB7RCp6hRSVZFYFZ8O0CIlXUEZAz0uXSzSoQ88wzx1NMlDNZSZPliw",
    quantity: "50 sticks",
    sellerName: "Sacred Store",
    sellerAddress: "1111 Temple Street, Haridwar, India",
    manufactureDate: new Date("2025-03-01"),
    expiryDate: new Date("2026-03-01"),
    disclaimer: "Burn safely away from flammable items.",
    description: "Fragrant dhoop sticks for pooja rituals.",
    createdBy: "admin4",
    categorySlug: "pooja-essentials",
    createdAt: new Date("2025-06-25")
  },
  {
    title: "Pooja Oil",
    price: 80,
    discountPrice: 70,
    imageUrl: "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcQyeD0ZQWywqg0mkAuOYTNTTUnQ651BdX_DAxXpOFw4-_HoGl78OW9n8Xjdd2czP4KcAgJlHlGxE9mC_begbR9G-BuMEL5sD_6L4yLzMf3dm_KO2CSYOkgU",
    quantity: "100 ml",
    sellerName: "Sacred Store",
    sellerAddress: "1111 Temple Street, Haridwar, India",
    manufactureDate: new Date("2025-04-01"),
    expiryDate: new Date("2026-04-01"),
    disclaimer: "Use only for lamps.",
    description: "Pure oil for lighting pooja lamps.",
    createdBy: "admin3",
    categorySlug: "pooja-essentials",
    createdAt: new Date("2025-06-26")
  },
  {
    title: "Sandalwood Powder",
    price: 150,
    discountPrice: 135,
    imageUrl: "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcS_ddYjzJWJyjNiEvtJpjhF4prsPDBY3zvs8XwojAdnF-8HZOJBsLJTO8lS6RQlhatj67lnQcQJeGapuqrsQT7tXCFS-FmjvSpNbNifPIHnQPedfG-e2jdQ4A",
    quantity: "50 g",
    sellerName: "Sacred Store",
    sellerAddress: "1111 Temple Street, Haridwar, India",
    manufactureDate: new Date("2025-05-01"),
    expiryDate: new Date("2026-05-01"),
    disclaimer: "Store in a dry place.",
    description: "Pure sandalwood powder for religious use.",
    createdBy: "admin4",
    categorySlug: "pooja-essentials",
    createdAt: new Date("2025-06-27")
  },
  {
    title: "Vermilion Powder",
    price: 40,
    discountPrice: 35,
    imageUrl: "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcSmkWPsUEcJ_R9cux0crUWZDfWnTpgPsT6ZV4ae1ct7YxE4HxioARyYsst8yKByDNCmWMHInk0AjRXhK9yN1EJCwXHMUyQ7Gkct0r-aOMSi",
    quantity: "50 g",
    sellerName: "Sacred Store",
    sellerAddress: "1111 Temple Street, Haridwar, India",
    manufactureDate: new Date("2025-05-15"),
    expiryDate: new Date("2026-05-15"),
    disclaimer: "For external use only.",
    description: "Bright vermilion powder for tilak ceremonies.",
    createdBy: "admin3",
    categorySlug: "pooja-essentials",
    createdAt: new Date("2025-06-28")
  },
  {
    title: "Cotton Wicks",
    price: 20,
    discountPrice: 18,
    imageUrl: "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcTvuAua85IKP3IsdIc_WMDAiYydFlWeFEBiI8Cu3QIH3OMZCVomMboqmULFXR9ylSjUen446k9eO6SMoxNz0qcwbVl7BbIb8gGjdeSngkLMqZX84VrcGaorEQ",
    quantity: "100 pieces",
    sellerName: "Sacred Store",
    sellerAddress: "1111 Temple Street, Haridwar, India",
    manufactureDate: new Date("2025-06-01"),
    expiryDate: new Date("2026-06-01"),
    disclaimer: "Store in a dry place.",
    description: "Pure cotton wicks for pooja lamps.",
    createdBy: "admin4",
    categorySlug: "pooja-essentials",
    createdAt: new Date("2025-06-29")
  },

  // 9. Baby & Hygiene
  {
    title: "Baby Diapers",
    price: 400,
    discountPrice: 360,
    imageUrl: "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcTuOOEcw3ugM6UNfS-JZztJ3bl9TeUGNWD_Xj2g62AScKGw1ezHWORlgCpA6MJNLTczVQcoW_nCNe6w2coDGexMSZinPXG_g0umYmldYFRxCjVnO5w9SUP-",
    quantity: "10 pieces",
    sellerName: "Baby Care",
    sellerAddress: "555 Care Lane, Chennai, India",
    manufactureDate: new Date("2025-01-01"),
    expiryDate: new Date("2026-01-01"),
    disclaimer: "Check for allergies before use.",
    description: "Soft and absorbent diapers for babies.",
    createdBy: "admin1",
    categorySlug: "baby-hygiene",
    createdAt: new Date("2025-06-17")
  },
  {
    title: "Baby Lotion",
    price: 200,
    discountPrice: 180,
    imageUrl: "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcSESt4DsSrWFkcQhAn-p578ffmEKZMBrxoQv0AFcMLZyTl56lLWrJ6bz5Bx-CHoYOfUiKe7_tFQ7Wm-3cz2Pa-WhXASMm8Oy17ko-Q-KfdfJjWCRseAzjkLJDviWRiACah8sZHIYHI&usqp=CAc",
    quantity: "200 ml",
    sellerName: "Baby Care",
    sellerAddress: "555 Care Lane, Chennai, India",
    manufactureDate: new Date("2025-02-01"),
    expiryDate: new Date("2026-02-01"),
    disclaimer: "For external use only.",
    description: "Gentle baby lotion for soft skin.",
    createdBy: "admin2",
    categorySlug: "baby-hygiene",
    createdAt: new Date("2025-06-18")
  },
  {
    title: "Baby Shampoo",
    price: 180,
    discountPrice: 160,
    imageUrl: "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcSr_Iq2ngT_CZoQZovs-TTjPOOVp7Py09VjP4eU-K9EaO3TpywK3xhUzVMnyyhAOSKoNaGosVzKWdv-lFDaVC2fCLyx3Up-O_AqOIMa8jlULI3svRVRC_3l",
    quantity: "200 ml",
    sellerName: "Baby Soft",
    sellerAddress: "1212 Care Road, Mumbai, India",
    manufactureDate: new Date("2025-03-01"),
    expiryDate: new Date("2026-03-01"),
    disclaimer: "Avoid contact with eyes.",
    description: "Gentle baby shampoo for soft hair.",
    createdBy: "admin3",
    categorySlug: "baby-hygiene",
    createdAt: new Date("2025-06-25")
  },
  {
    title: "Baby Wipes",
    price: 150,
    discountPrice: 135,
    imageUrl: "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcTSGaVyWwvOA84c9veJxg4pzPNk4esSXYcKo75OE3pJWeGTzB_dVdzw6a7WvrUn7-fDdleX4m0vxtC8JqQVIeQjtKU_eg3eSQ38vcfKHOTYhSUdGwFek_dYFl3U",
    quantity: "80 pieces",
    sellerName: "Baby Soft",
    sellerAddress: "1212 Care Road, Mumbai, India",
    manufactureDate: new Date("2025-04-01"),
    expiryDate: new Date("2026-04-01"),
    disclaimer: "For external use only.",
    description: "Soft baby wipes for gentle cleaning.",
    createdBy: "admin4",
    categorySlug: "baby-hygiene",
    createdAt: new Date("2025-06-26")
  },
  {
    title: "Baby Powder",
    price: 120,
    discountPrice: 100,
    imageUrl: "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcTzJilrOw884Qh1Rzd0FA_2R3xKeXId2FXF4zgmcORTdYnU9aCMR6nYlZ_5ykBE3GxclypIQ3Ly-zXU5xBX8dbI2xKIgcDKFWMkdl2iQR0COcvg6HrBt3in",
    quantity: "200 g",
    sellerName: "Baby Soft",
    sellerAddress: "1212 Care Road, Mumbai, India",
    manufactureDate: new Date("2025-05-01"),
    expiryDate: new Date("2026-05-01"),
    disclaimer: "Keep away from nose and mouth.",
    description: "Mild baby powder for dry skin.",
    createdBy: "admin3",
    categorySlug: "baby-hygiene",
    createdAt: new Date("2025-06-27")
  },
  {
    title: "Diaper Rash Cream",
    price: 200,
    discountPrice: 180,
    imageUrl: "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcRFNUQq8UPWyFUK8gNnpzyPXQKjc7erBVvd8c6TMIXhFraxvRZwRGqw-Lpt9Qa2JnyyO19N8aGToJ1aJiIuWq4QvHlZ2XqLEv8UlHWt48vht6dRLO_HD10",
    quantity: "50 g",
    sellerName: "Baby Soft",
    sellerAddress: "1212 Care Road, Mumbai, India",
    manufactureDate: new Date("2025-05-15"),
    expiryDate: new Date("2026-05-15"),
    disclaimer: "Consult a doctor if irritation persists.",
    description: "Soothing cream for diaper rash relief.",
    createdBy: "admin4",
    categorySlug: "baby-hygiene",
    createdAt: new Date("2025-06-28")
  },
  {
    title: "Baby Oil",
    price: 220,
    discountPrice: 200,
    imageUrl: "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcSBjJaVf-a72Cez0OQEQ_LyBXdNft8MW_XchcY3aESE_AJ3tBh5WmiiRkLFaFn02Ufnl308-84Ci4H2MsCvbDSkXRof0EQWn9Pkxk7xVr7TuSyX3PTC1vEJXw",
    quantity: "100 ml",
    sellerName: "Baby Soft",
    sellerAddress: "1212 Care Road, Mumbai, India",
    manufactureDate: new Date("2025-06-01"),
    expiryDate: new Date("2026-06-01"),
    disclaimer: "For external use only.",
    description: "Gentle baby oil for massage and hydration.",
    createdBy: "admin3",
    categorySlug: "baby-hygiene",
    createdAt: new Date("2025-06-29")
  },

  // 10. Meat & Eggs
  {
    title: "Fresh Chicken",
    price: 250,
    discountPrice: 230,
    imageUrl: "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcTLzmhTzl0orvMWjfmDG1caFvgilj2RkJjYG8SbCXCbD9SQbp-KA33LsKUQpVMv5B4DdPTtKxeFrPMB23rbHDhn9Bz7JB9yjWAz-6W0dyunvu1NzpgefuSXwg",
    quantity: "1 kg",
    sellerName: "Fresh Meats",
    sellerAddress: "666 Meat Market, Hyderabad, India",
    manufactureDate: new Date("2025-06-25"),
    expiryDate: new Date("2025-07-02"),
    disclaimer: "Refrigerate immediately.",
    description: "Farm-fresh chicken, hygienically packed.",
    createdBy: "admin1",
    categorySlug: "meat-eggs",
    createdAt: new Date("2025-06-19")
  },
  {
    title: "Farm Eggs",
    price: 80,
    discountPrice: 75,
    imageUrl: "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcTNqcbyIFtbTwZ84cNc55yunS5-tJxFY6YqpwZw9zZhtfYa-7RZvg4Oh9dPVYmYYL3_BMEqg784nxjkBPJrPTSxZfTuoJi7MAPG16QH-P5ERmlo5HI-56sv",
    quantity: "12 pieces",
    sellerName: "Fresh Meats",
    sellerAddress: "666 Meat Market, Hyderabad, India",
    manufactureDate: new Date("2025-06-20"),
    expiryDate: new Date("2025-07-20"),
    disclaimer: "Check for cracks before use.",
    description: "Fresh farm eggs, rich in protein.",
    createdBy: "admin2",
    categorySlug: "meat-eggs",
    createdAt: new Date("2025-06-20")
  },
  {
    title: "Mutton Curry Cut",
    price: 600,
    discountPrice: 550,
    imageUrl: "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcSJxIGX0qEbi0V6DGCnE7_SJHWYCN7YwKiHie2YxGZUxwCpqVWHS_4cpsVQk4daF9f0hiuQMIOVjNQX0oYpaQhvji_JQZOTsaeAWhrAcYIXEoxagK9HfwT1jQ",
    quantity: "1 kg",
    sellerName: "Meat Fresh",
    sellerAddress: "1313 Meat Market, Kolkata, India",
    manufactureDate: new Date("2025-06-28"),
    expiryDate: new Date("2025-07-05"),
    disclaimer: "Refrigerate immediately.",
    description: "Fresh mutton curry cut for rich curries.",
    createdBy: "admin4",
    categorySlug: "meat-eggs",
    createdAt: new Date("2025-06-25")
  },
  {
    title: "Fish Fillets",
    price: 400,
    discountPrice: 360,
    imageUrl: "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcQqUfvKM_WStEYlbjwxJW-Qcy_GSNpnA_PzPcwmqERqm4DIrYvDlBKIdiagnUdDNx1WGqTXx-0Nqs2CjnwCQMflxxSfb1BgoXhYAIL1vw4cvb75b27vhHQeClA",
    quantity: "500 g",
    sellerName: "Meat Fresh",
    sellerAddress: "1313 Meat Market, Kolkata, India",
    manufactureDate: new Date("2025-06-29"),
    expiryDate: new Date("2025-07-06"),
    disclaimer: "Store in a freezer.",
    description: "Fresh fish fillets for grilling or frying.",
    createdBy: "admin3",
    categorySlug: "meat-eggs",
    createdAt: new Date("2025-06-26")
  },
  {
    title: "Organic Eggs",
    price: 100,
    discountPrice: 90,
    imageUrl: "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcRRGY49EPhYfiwUbibKAG3sn3pEzVMoPyffFRlXW9W9GVYn01rSW1TpuhKkLJaS98A3dQqH9kWcS2gMCRE2SWq6_qEqG49M890Vp_MkVyiYxghJrJCT4CQy",
    quantity: "12 pieces",
    sellerName: "Meat Fresh",
    sellerAddress: "1313 Meat Market, Kolkata, India",
    manufactureDate: new Date("2025-06-27"),
    expiryDate: new Date("2025-07-27"),
    disclaimer: "Check for freshness.",
    description: "Organic eggs from free-range chickens.",
    createdBy: "admin4",
    categorySlug: "meat-eggs",
    createdAt: new Date("2025-06-27")
  },
  

  // 11. Pet Supplies
  {
    title: "Dog Food",
    price: 500,
    discountPrice: 450,
    imageUrl: "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcQY3um09JhxDxPAh-GYiT2GuTeBraPqrh_hX2h9H4qYNqAaXyWngy1QryhHy2BZATPs1kSoNJ8rOLVkcz-JzIEK7nUHvgHV_PGkMDcT5Pxo8vWhuXmnK_Fe",
    quantity: "2 kg",
    sellerName: "Pet Store",
    sellerAddress: "777 Pet Lane, Pune, India",
    manufactureDate: new Date("2025-03-01"),
    expiryDate: new Date("2026-03-01"),
    disclaimer: "Consult a vet for dietary needs.",
    description: "Nutritious dog food for adult dogs.",
    createdBy: "admin1",
    categorySlug: "pet-supplies",
    createdAt: new Date("2025-06-21")
  },
  {
    title: "Cat Litter",
    price: 300,
    discountPrice: 270,
    imageUrl: "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcTsU9__eJBVkp65qyqWX62AOmOFitG07CBTtKttRcjyBXcIIsuviCzc3AOgBOZz2hlOVyVxxAxlkluyJi9z1cU4pMPtPCFfaTcNB6jHYBBCItGtTNwNPA97",
    quantity: "5 kg",
    sellerName: "Pet Store",
    sellerAddress: "777 Pet Lane, Pune, India",
    manufactureDate: new Date("2025-04-01"),
    expiryDate: new Date("2026-04-01"),
    disclaimer: "Keep in a dry place.",
    description: "Odor-control cat litter for hygiene.",
    createdBy: "admin2",
    categorySlug: "pet-supplies",
    createdAt: new Date("2025-06-22")
  },
  {
    title: "Dog Biscuits",
    price: 200,
    discountPrice: 180,
    imageUrl: "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcQ2BeQOd-7uaGCyskKfv1hEj_NFg-Up8Tc-0JsbeeDyoeO98cc4A98EovRLRL8CX60LowZCTjFlSGnS9Qg8HWKvWqlk8xHhKLNmsT8Jb_8",
    quantity: "500 g",
    sellerName: "Pet Needs",
    sellerAddress: "1414 Pet Street, Delhi, India",
    manufactureDate: new Date("2025-03-01"),
    expiryDate: new Date("2026-03-01"),
    disclaimer: "Consult a vet for dietary needs.",
    description: "Crunchy dog biscuits for training treats.",
    createdBy: "admin3",
    categorySlug: "pet-supplies",
    createdAt: new Date("2025-06-25")
  },
  {
    title: "Cat Food",
    price: 400,
    discountPrice: 360,
    imageUrl: "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcQLgRl4a-lkkgrR6jHG7K9x28P44kZsj40gPmdEE0HzCxYPV4EROMBp_VFrXOV4CbQ50Q70hHWZq3qhjPDxeED7dBEHGx9hzSEPZ-syJbOp5yqVl3SYu2YQ",
    quantity: "1 kg",
    sellerName: "Pet Needs",
    sellerAddress: "1414 Pet Street, Delhi, India",
    manufactureDate: new Date("2025-04-01"),
    expiryDate: new Date("2026-04-01"),
    disclaimer: "Store in a dry place.",
    description: "Nutritious cat food for adult cats.",
    createdBy: "admin4",
    categorySlug: "pet-supplies",
    createdAt: new Date("2025-06-26")
  },
  {
    title: "Pet Shampoo",
    price: 250,
    discountPrice: 225,
    imageUrl: "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcRWGHVGpp2Rb1ZGHMOT73HEzcVymc0MyQ_z75t-mEg2KyfhM_N4-xv3GUR3wbeN39GuAI2tSWRSJys5SM_B6Qabohx0hRzxSIi34iDoTnad5Puuda2u1nl6",
    quantity: "200 ml",
    sellerName: "Pet Needs",
    sellerAddress: "1414 Pet Street, Delhi, India",
    manufactureDate: new Date("2025-05-01"),
    expiryDate: new Date("2026-05-01"),
    disclaimer: "For external use only.",
    description: "Gentle pet shampoo for a clean coat.",
    createdBy: "admin3",
    categorySlug: "pet-supplies",
    createdAt: new Date("2025-06-27")
  },
  {
    title: "Dog Chew Toys",
    price: 300,
    discountPrice: 270,
    imageUrl: "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcSz4X0IhrzuN4YGphKOenyR0IDgZ9FcVHFLP1BBoEuDYkDxEwkTKTm5CJEg97CcxoIhElKNjvXqIFNoHgC6pCe9LivlSWxIkJavtGQ-ps2jXey91d4K5j6HZSI",
    quantity: "1 piece",
    sellerName: "Pet Needs",
    sellerAddress: "1414 Pet Street, Delhi, India",
    manufactureDate: new Date("2025-05-15"),
    expiryDate: new Date("2026-05-15"),
    disclaimer: "Supervise during use.",
    description: "Durable chew toys for dogs.",
    createdBy: "admin4",
    categorySlug: "pet-supplies",
    createdAt: new Date("2025-06-28")
  },
  {
    title: "Fish Food",
    price: 150,
    discountPrice: 135,
    imageUrl: "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcQZbLIOoBWYpT5neanyyAlsCDdUH5elPaQpFmGl_FVhkR6Kz4Ve_tCv8nika5Dz4khffIDAK_baPd6FdejQ0yMCmpqgGPYU0Z-JHELqfNIHgEZ_crkbo3Bz",
    quantity: "100 g",
    sellerName: "Pet Needs",
    sellerAddress: "1414 Pet Street, Delhi, India",
    manufactureDate: new Date("2025-06-01"),
    expiryDate: new Date("2026-06-01"),
    disclaimer: "Feed as per instructions.",
    description: "Nutritious fish food for healthy fish.",
    createdBy: "admin3",
    categorySlug: "pet-supplies",
    createdAt: new Date("2025-06-29")
  },

  // 12. Bakery & Desserts
  {
    title: "Chocolate Cake",
    price: 400,
    discountPrice: 360,
    imageUrl: "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcTKnO2nyzXVWboECtTAw9TJc3l8KCaKMjpHCtP6KDkUM4QI2VfZ3Tg9_ildf05Cgh-F0Wx5rDv7vo096QABMyp3CWDfYFpr9HNu9hjSpBX1iEs-k48wsytS5Q",
    quantity: "500 g",
    sellerName: "Sweet Bakery",
    sellerAddress: "888 Bakery Street, Mumbai, India",
    manufactureDate: new Date("2025-06-25"),
    expiryDate: new Date("2025-07-02"),
    disclaimer: "Contains dairy and gluten.",
    description: "Rich chocolate cake for all occasions.",
    createdBy: "admin1",
    categorySlug: "bakery-desserts",
    createdAt: new Date("2025-06-23")
  },
  {
    title: "Butter Cookies",
    price: 150,
    discountPrice: 135,
    imageUrl: "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcRMoKlFHRAZoyPYNMc1BgjDYCMrydrV3MZSNVODTADB8FgszUFdSN5EtetVHzIyV5EnMdzcZeCPrnbeoqiZEzM7FiYHMIg28LGa5-ejQ2wnMN6AVw-3fi_3BQ",
    quantity: "200 g",
    sellerName: "Sweet Bakery",
    sellerAddress: "888 Bakery Street, Mumbai, India",
    manufactureDate: new Date("2025-06-20"),
    expiryDate: new Date("2025-09-20"),
    disclaimer: "Contains dairy and gluten.",
    description: "Crispy butter cookies, perfect with tea.",
    createdBy: "admin2",
    categorySlug: "bakery-desserts",
    createdAt: new Date("2025-06-24")
  },
  {
    title: "Vanilla Cake",
    price: 450,
    discountPrice: 400,
    imageUrl: "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcSQO4McTrFpnPg7JasxYYqiZEHRnaopqtPY9UMnjXnGAmmnNkNp-rotelycWOHRJC7y08dyXzsvoBCU_uFU5mii48XBP0ejNb2MHq2WUaeIOeit0ONHjIzI",
    quantity: "500 g",
    sellerName: "Sweet Delight",
    sellerAddress: "1515 Bakery Lane, Pune, India",
    manufactureDate: new Date("2025-06-28"),
    expiryDate: new Date("2025-07-05"),
    disclaimer: "Contains dairy and gluten.",
    description: "Soft vanilla cake for celebrations.",
    createdBy: "admin4",
    categorySlug: "bakery-desserts",
    createdAt: new Date("2025-06-25")
  },
  {
    title: "Chocolate Muffins",
    price: 200,
    discountPrice: 180,
    imageUrl: "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcSQm9BEZyr3aIUn-TP50CIJEMv6YTIhdcii7x_lW1qKRxiTmcYBqrx9fyNwBmj_RYAyAlCS7XN0JEEV1hsFm3kuLmkeNEKqyHgtbIVtUYV154jLYjpvY71V",
    quantity: "4 pieces",
    sellerName: "Sweet Delight",
    sellerAddress: "1515 Bakery Lane, Pune, India",
    manufactureDate: new Date("2025-06-27"),
    expiryDate: new Date("2025-07-04"),
    disclaimer: "Contains dairy and gluten.",
    description: "Rich chocolate muffins for a sweet treat.",
    createdBy: "admin3",
    categorySlug: "bakery-desserts",
    createdAt: new Date("2025-06-26")
  },
  {
    title: "Fruit Pastry",
    price: 100,
    discountPrice: 90,
    imageUrl: "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcRGA69M_Aj22nGM2HV0UjrsLQJXjPYd4mUjNPKjI86KiK8QpSj-YzgYXsGN3IdKqjWSKYdJdh1AF1XjlB4ICc6dFNksVUf4_EdA9boXDCZ3CBYuG2p-OvaEiQ",
    quantity: "2 pieces",
    sellerName: "Sweet Delight",
    sellerAddress: "1515 Bakery Lane, Pune, India",
    manufactureDate: new Date("2025-06-28"),
    expiryDate: new Date("2025-07-03"),
    disclaimer: "Contains dairy.",
    description: "Fresh fruit pastry with creamy topping.",
    createdBy: "admin4",
    categorySlug: "bakery-desserts",
    createdAt: new Date("2025-06-27")
  },
  {
    title: "Brownie",
    price: 150,
    discountPrice: 135,
    imageUrl: "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcQTef191iVg0P0RzCvip-RnbcGOQA7IsqsxMvZRQNKztPcBefOwTO_aZu6wrG6XRw-w9TNtGaJNsKS2WM5ofvhKUhDw7AVmtp_g3rxfaM668dnLtq1KUGP8",
    quantity: "200 g",
    sellerName: "Sweet Delight",
    sellerAddress: "1515 Bakery Lane, Pune, India",
    manufactureDate: new Date("2025-06-27"),
    expiryDate: new Date("2025-07-04"),
    disclaimer: "Contains dairy and nuts.",
    description: "Fudgy brownie for chocolate lovers.",
    createdBy: "admin3",
    categorySlug: "bakery-desserts",
    createdAt: new Date("2025-06-28")
  },
  {
    title: "Rusk",
    price: 80,
    discountPrice: 70,
    imageUrl: "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcTDfNdRUfscb537E1TuAe5OP6G3Am-xU9eztiR9bYZEgwxheKhwP29xym96pk8OF272SWQ3Ti50wVS83VxT_GgbOOgpD_hNhxl8IkSsATJETD6-qCNeecSV",
    quantity: "200 g",
    sellerName: "Sweet Delight",
    sellerAddress: "1515 Bakery Lane, Pune, India",
    manufactureDate: new Date("2025-06-25"),
    expiryDate: new Date("2025-09-25"),
    disclaimer: "Contains gluten.",
    description: "Crispy rusk for tea-time snacking.",
    createdBy: "admin4",
    categorySlug: "bakery-desserts",
    createdAt: new Date("2025-06-29")
  },

  // 13. Sauces & Spreads
  {
    title: "Tomato Ketchup",
    price: 120,
    discountPrice: 100,
    imageUrl: "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcT7N11NZY56HaIUC3jbE_8m6rYFgKRK5IfENEZomI1Ov2vEYuVYi1-h5m9DqA7C32W61g1eSL-hZFfbtr14QdHMslnJzeL6qmFuJbTs7E3by07lZ9rsry9mpQhttps://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcSblhMCBl8dwThZGokQbkoeoTGAdKUazvRvEVQ0mVdz-2XnGx98AFZ_xDMrUeZe18vYecAoCJi3mE2skhSgptpqSRTbGcZzWRbWdkSG-3g84k8pVZyJbQQ-TQ",
    quantity: "500 g",
    sellerName: "Tasty Condiments",
    sellerAddress: "999 Sauce Lane, Delhi, India",
    manufactureDate: new Date("2025-05-01"),
    expiryDate: new Date("2026-05-01"),
    disclaimer: "Refrigerate after opening.",
    description: "Tangy tomato ketchup for all dishes.",
    createdBy: "admin1",
    categorySlug: "sauces-spreads",
    createdAt: new Date("2025-06-25")
  },
  {
    title: "Peanut Butter",
    price: 200,
    discountPrice: 180,
    imageUrl: "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcSrWQDZWh5hIyAZwIpNWRfCjmwvEIwY7Kj7LXKoxEBWENJzbJBOt1mV9V20Mkusbx6CvZVcZPoGujU6ANrWU6UgFdNLz0m2Mkhmg-Sd1jyPlrjkn4X1lpSbZQ",
    quantity: "400 g",
    sellerName: "Tasty Condiments",
    sellerAddress: "999 Sauce Lane, Delhi, India",
    manufactureDate: new Date("2025-05-15"),
    expiryDate: new Date("2026-05-15"),
    disclaimer: "Contains nuts.",
    description: "Creamy peanut butter for healthy snacking.",
    createdBy: "admin2",
    categorySlug: "sauces-spreads",
    createdAt: new Date("2025-06-26")
  },
  {
    title: "Soy Sauce",
    price: 150,
    discountPrice: 135,
    imageUrl: "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcRltb3BrxLQKyG0BjyKZkLZNUhkbdN_Q7j_vTdetwIysZ7A4TgzBOnqoGvY4jg-GDvq804QRsTmVDRUlL7LUJyZp-znxFOOBE1pe1U__JfC59BnpiZr66EJ",
    quantity: "200 ml",
    sellerName: "Tasty Sauces",
    sellerAddress: "1616 Sauce Street, Mumbai, India",
    manufactureDate: new Date("2025-03-01"),
    expiryDate: new Date("2026-03-01"),
    disclaimer: "Refrigerate after opening.",
    description: "Rich soy sauce for Asian dishes.",
    createdBy: "admin3",
    categorySlug: "sauces-spreads",
    createdAt: new Date("2025-06-25")
  },
  {
    title: "Chocolate Spread",
    price: 250,
    discountPrice: 225,
    imageUrl: "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcTx3khz7ODBYRI5wrDhBxwhm3YYDnHTxS6OpNH94OWpZ9F5_2AnfUmXpiHDZh7LCEUJCUvK6k2qQKAOSzWgiJdrUj6yfeNJRosuhDR5JhtLDuKN--id08rT",
    quantity: "200 g",
    sellerName: "Tasty Sauces",
    sellerAddress: "1616 Sauce Street, Mumbai, India",
    manufactureDate: new Date("2025-04-01"),
    expiryDate: new Date("2026-04-01"),
    disclaimer: "Contains dairy and nuts.",
    description: "Creamy chocolate spread for breakfast.",
    createdBy: "admin4",
    categorySlug: "sauces-spreads",
    createdAt: new Date("2025-06-26")
  },
  {
    title: "Mayonnaise",
    price: 120,
    discountPrice: 100,
    imageUrl: "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcS7H0LVChmrePMsfZ1ZWFEgkuPq1B4oIXmdTA-x0QrEs0fZTfzYNX5Ecgftc0soyO46P3BfR7QSAzGuV1zYpFmziPMawsbcoxYiAcAr4a-vzITb_B9yDrqj",
    quantity: "250 g",
    sellerName: "Tasty Sauces",
    sellerAddress: "1616 Sauce Street, Mumbai, India",
    manufactureDate: new Date("2025-05-01"),
    expiryDate: new Date("2026-05-01"),
    disclaimer: "Refrigerate after opening.",
    description: "Smooth mayonnaise for sandwiches and salads.",
    createdBy: "admin3",
    categorySlug: "sauces-spreads",
    createdAt: new Date("2025-06-27")
  },
  
  {
    title: "Jam",
    price: 140,
    discountPrice: 125,
    imageUrl: "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcR7gAdKoM7vejiM5YrX5LRyR41n_k0Oe7dQLHIZceGzdJ8vNLBdsaHNWbbkGIJ2_FkVFANl46KKYird6RgSI3T8OyrcNzDNOIaCskn2H73K0NCfRm7OaZ60",
    quantity: "300 g",
    sellerName: "Tasty Sauces",
    sellerAddress: "1616 Sauce Street, Mumbai, India",
    manufactureDate: new Date("2025-06-01"),
    expiryDate: new Date("2026-06-01"),
    disclaimer: "Store in a cool place.",
    description: "Sweet mixed fruit jam for breakfast.",
    createdBy: "admin3",
    categorySlug: "sauces-spreads",
    createdAt: new Date("2025-06-29")
  },

  // 14. Dry Fruits & Nuts
  {
    title: "Almonds",
    price: 600,
    discountPrice: 550,
    imageUrl: "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcSGDcH49e-eUxX9H04QYO4visXrK_KAMcM50i_hzI9lzKGyDo261UuacyPYvXYheKFSfT9Jc09L-Wlh9lIoawPphdlVld6rp_-SFKtfnaqcPVdfryuXIRvzgg",
    quantity: "500 g",
    sellerName: "Nutty Delights",
    sellerAddress: "1010 Nut Market, Kashmir, India",
    manufactureDate: new Date("2025-04-01"),
    expiryDate: new Date("2026-04-01"),
    disclaimer: "Contains nuts.",
    description: "Premium quality almonds, rich in nutrients.",
    createdBy: "admin1",
    categorySlug: "dry-fruits-nuts",
    createdAt: new Date("2025-06-27")
  },
  {
    title: "Cashews",
    price: 700,
    discountPrice: 650,
    imageUrl: "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcS5HUDVeEKB4lURHYs7F_DzUuz5rjOIfq4nTQbDm6manyflERDYtL5HMAGL1FztTN2RUv2P976dfo2qv_F6O8vvInE-eDFh_djY_cpCGe2sANgjg-9ou7RY",
    quantity: "500 g",
    sellerName: "Nutty Delights",
    sellerAddress: "1010 Nut Market, Kashmir, India",
    manufactureDate: new Date("2025-04-15"),
    expiryDate: new Date("2026-04-15"),
    disclaimer: "Contains nuts.",
    description: "Crunchy cashews, perfect for snacking.",
    createdBy: "admin2",
    categorySlug: "dry-fruits-nuts",
    createdAt: new Date("2025-06-28")
  },
  {
    title: "Pistachios",
    price: 800,
    discountPrice: 720,
    imageUrl: "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcTgz6CB-DpyiAtXHFCGmT5LRlxPf4QnRCfSkYLVM5F2xiN45E1hxfxB8RhoMYd-tGWVp1pTP-btCwFN5-pP1mtRkiT4jDo-99tdaLSNa5io0RP6WCiP2E6gcQ",
    quantity: "500 g",
    sellerName: "Nut House",
    sellerAddress: "1717 Nut Market, Kashmir, India",
    manufactureDate: new Date("2025-03-01"),
    expiryDate: new Date("2026-03-01"),
    disclaimer: "Contains nuts.",
    description: "Premium pistachios for healthy snacking.",
    createdBy: "admin4",
    categorySlug: "dry-fruits-nuts",
    createdAt: new Date("2025-06-25")
  },
  {
    title: "Raisins",
    price: 200,
    discountPrice: 180,
    imageUrl: "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcR0nvNUeVrCNztkgxlKn71joEQaaNB5WWjQxIIvgJBD8w2oWH-SFbw0W65BaUHnxdhiysZkyZ11tR4KhpS9gWsBr3O6V471Lyzb2Bn8abAsOXrj3CpRVtVjmw",
    quantity: "500 g",
    sellerName: "Nut House",
    sellerAddress: "1717 Nut Market, Kashmir, India",
    manufactureDate: new Date("2025-04-01"),
    expiryDate: new Date("2026-04-01"),
    disclaimer: "Store in a cool place.",
    description: "Sweet raisins for desserts and snacks.",
    createdBy: "admin3",
    categorySlug: "dry-fruits-nuts",
    createdAt: new Date("2025-06-26")
  },
  {
    title: "Walnuts",
    price: 900,
    discountPrice: 810,
    imageUrl: "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcR5rSP6pPyhdexcG9U0vqTQiYEZpWiJ0lFNyrEbrqivvLl0k7NfXi6Y_9m8MZjRulmGffXKvWtp5V8ax2NRLHNt8LD_c3XUer_nwuwstF7PopPouOjnqYsd",
    quantity: "500 g",
    sellerName: "Nut House",
    sellerAddress: "1717 Nut Market, Kashmir, India",
    manufactureDate: new Date("2025-05-01"),
    expiryDate: new Date("2026-05-01"),
    disclaimer: "Contains nuts.",
    description: "Crunchy walnuts rich in omega-3.",
    createdBy: "admin4",
    categorySlug: "dry-fruits-nuts",
    createdAt: new Date("2025-06-27")
  },
  {
    title: "Dried Apricots",
    price: 400,
    discountPrice: 360,
    imageUrl: "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcTZUrRy5Utl65ZFx-rkZ4bfuOf8Xzjei5C1j4nACcZVAptanTczCv1-mhGcNIdNH_uIFjceHd6Ox4aYqjUkKfwnuZzNiVBoLrhUNG254fTnk_Wb9mG5C9Vt",
    quantity: "250 g",
    sellerName: "Nut House",
    sellerAddress: "1717 Nut Market, Kashmir, India",
    manufactureDate: new Date("2025-05-15"),
    expiryDate: new Date("2026-05-15"),
    disclaimer: "Store in a dry place.",
    description: "Sweet dried apricots for healthy snacking.",
    createdBy: "admin3",
    categorySlug: "dry-fruits-nuts",
    createdAt: new Date("2025-06-28")
  },
  {
    title: "Mixed Nuts",
    price: 600,
    discountPrice: 540,
    imageUrl: "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcQ11bw_gBEagFnKlBDL5MsgCPrYogww_Xq98f3Y0Xq3Nq0PH3TYiBt81IezON3il7CSgE7pL7ZfU9pbbdwuI4Bquw2AWyJU-WixVpqVe6V-wvbyNQW_nHK2hA",
    quantity: "500 g",
    sellerName: "Nut House",
    sellerAddress: "1717 Nut Market, Kashmir, India",
    manufactureDate: new Date("2025-06-01"),
    expiryDate: new Date("2026-06-01"),
    disclaimer: "Contains nuts.",
    description: "Assorted mixed nuts for a nutritious snack.",
    createdBy: "admin4",
    categorySlug: "dry-fruits-nuts",
    createdAt: new Date("2025-06-29")
  },

  // 15. Pickles & Pastes
  {
    title: "Mango Pickle",
    price: 150,
    discountPrice: 135,
    imageUrl: "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcT1aEokrh0wzNz5bHKpuvLk6polPEdJ5XiY0QQVGOagi74Lm26_4nrsV7a06HGwTqnYVNMYAw-was5H04SldjE4DPiDLMJueJX7bBbfwtU",
    quantity: "400 g",
    sellerName: "Tasty Pickles",
    sellerAddress: "1111 Pickle Lane, Gujarat, India",
    manufactureDate: new Date("2025-03-01"),
    expiryDate: new Date("2026-03-01"),
    disclaimer: "Store in a cool, dry place.",
    description: "Spicy mango pickle, homemade style.",
    createdBy: "admin1",
    categorySlug: "pickles-pastes",
    createdAt: new Date("2025-06-29")
  },
  {
    title: "Ginger Garlic Paste",
    price: 100,
    discountPrice: 90,
    imageUrl: "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcTOpLxlzXwDcQkTUZmLC-hjGgDtBWYxGcXMDSQ7B33D_mgEcdIO00QJd34h-zALEviSizwYn0d-ZIM0APkIM5xiFZI6XzMZ-tmtr0exYCbqRlE3XqNMcf1_",
    quantity: "200 g",
    sellerName: "Tasty Pickles",
    sellerAddress: "1111 Pickle Lane, Gujarat, India",
    manufactureDate: new Date("2025-03-15"),
    expiryDate: new Date("2026-03-15"),
    disclaimer: "Refrigerate after opening.",
    description: "Fresh ginger garlic paste for cooking.",
    createdBy: "admin2",
    categorySlug: "pickles-pastes",
    createdAt: new Date("2025-06-30")
  },
  {
    title: "Mixed Pickle",
    price: 160,
    discountPrice: 140,
    imageUrl: "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcS0rxNjJNrZ70M87Si6bwIcUSv36eVK74TnHwzjGoQ6NKaS6htMc7GnVm7o6wyjpcd6POW6LLQb4Pn1blHZeE_Rr_8Bs2IMmsoW9_EAd266",
    quantity: "400 g",
    sellerName: "Pickle House",
    sellerAddress: "1818 Pickle Lane, Gujarat, India",
    manufactureDate: new Date("2025-03-01"),
    expiryDate: new Date("2026-03-01"),
    disclaimer: "Store in a cool place.",
    description: "Spicy mixed vegetable pickle.",
    createdBy: "admin3",
    categorySlug: "pickles-pastes",
    createdAt: new Date("2025-06-25")
  },
  {
    title: "Garlic Pickle",
    price: 150,
    discountPrice: 135,
    imageUrl: "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcSucSIljc9iVBXfCMR2_yXBwLmY5al285y3AhbGLXdGMvI2f05jgZuryIO8x4C0OwXZZhw2pM6Iz1ZpiXJFQCXasfd6ySg3usmd2bZ3CBh4UxobLtakzdJF",
    quantity: "400 g",
    sellerName: "Pickle House",
    sellerAddress: "1818 Pickle Lane, Gujarat, India",
    manufactureDate: new Date("2025-04-01"),
    expiryDate: new Date("2026-04-01"),
    disclaimer: "Refrigerate after opening.",
    description: "Flavorful garlic pickle for meals.",
    createdBy: "admin4",
    categorySlug: "pickles-pastes",
    createdAt: new Date("2025-06-26")
  },
  {
    title: "Tomato Paste",
    price: 100,
    discountPrice: 90,
    imageUrl: "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcTFKoiNFVcY96Eium9nmwR_cqBdwmmkg5DJKRZqHtwLy1O5LzwSAtDsuah8trV1PuEV1RSABW3VkOYKqA-QIrPeCP9UaI8wilETbOuNGxaW3la1Fv8FGDdmsg",
    quantity: "200 g",
    sellerName: "Pickle House",
    sellerAddress: "1818 Pickle Lane, Gujarat, India",
    manufactureDate: new Date("2025-05-01"),
    expiryDate: new Date("2026-05-01"),
    disclaimer: "Refrigerate after opening.",
    description: "Thick tomato paste for cooking.",
    createdBy: "admin3",
    categorySlug: "pickles-pastes",
    createdAt: new Date("2025-06-27")
  },
  {
    title: "Green Chilli Pickle",
    price: 140,
    discountPrice: 125,
    imageUrl: "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcSKt1VFxBI_KiZxZse99swFH8Ba_FahZ3VQy8zvWcYBG8oB4CqbzMWuZK85exdLaZ7d9lfMajeN6kVHmiyxbGnPd8Bf7tGTcVGTfmFUHw-DjaPUDUoUibDZ",
    quantity: "400 g",
    sellerName: "Pickle House",
    sellerAddress: "1818 Pickle Lane, Gujarat, India",
    manufactureDate: new Date("2025-05-15"),
    expiryDate: new Date("2026-05-15"),
    disclaimer: "Store in a cool place.",
    description: "Spicy green chilli pickle for bold flavors.",
    createdBy: "admin4",
    categorySlug: "pickles-pastes",
    createdAt: new Date("2025-06-28")
  },
  {
    title: "Tamarind Paste",
    price: 120,
    discountPrice: 100,
    imageUrl: "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcQXyFbSRfZIXTyGqtx6LVcnyHmgykwvxkqg71lRdoBxomSIguCCRfVEJ2r4HJophgwr6C9mzn1VOIWIxuWZ6OsmzH7ral5mZ1gZWfX0JW_ZAP_mQ-elfa78",
    quantity: "200 g",
    sellerName: "Pickle House",
    sellerAddress: "1818 Pickle Lane, Gujarat, India",
    manufactureDate: new Date("2025-06-01"),
    expiryDate: new Date("2026-06-01"),
    disclaimer: "Refrigerate after opening.",
    description: "Tangy tamarind paste for chutneys.",
    createdBy: "admin3",
    categorySlug: "pickles-pastes",
    createdAt: new Date("2025-06-29")
  },

  // 16. Fruits & Vegetables
  {
    title: "Fresh Apples",
    price: 200,
    discountPrice: 180,
    imageUrl: "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcRV3RfoAtlp1pLd-dEooRsvy_yTZw1bz3t91wiD-xvcAne__nD0WtmK21fbKqfMqB0EyEapJf_PrwtJAM2_USlCo5Rz-yQ7F_pGnOg0VbSLpUXeCEXzhl0Nig",
    quantity: "1 kg",
    sellerName: "Fresh Farms",
    sellerAddress: "1212 Farm Road, Himachal, India",
    manufactureDate: new Date("2025-06-20"),
    expiryDate: new Date("2025-07-20"),
    disclaimer: "Store in a cool place.",
    description: "Crisp and juicy apples from Himachal.",
    createdBy: "admin1",
    categorySlug: "fruits-vegetables",
    createdAt: new Date("2025-06-20")
  },
    // Completing Fruits & Vegetables category with additional products
  {
    title: "Organic Carrots",
    price: 80,
    discountPrice: 70,
    imageUrl: "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcTtbF5FS-oo_XKwBg3gJf4d_OGJcX9OcgcWew20bPDOLrNgEBip-ka3IzW-vZqQ5328axnb1KjD9l-hkhnE0CUbosZhVJ0hHb0VGBU1WEUzf7G59jY83w7CsA",
    quantity: "1 kg",
    sellerName: "Fresh Farms",
    sellerAddress: "1212 Farm Road, Himachal, India",
    manufactureDate: new Date("2025-06-20"),
    expiryDate: new Date("2025-07-20"),
    disclaimer: "Store in a cool place.",
    description: "Fresh organic carrots, rich in vitamins.",
    createdBy: "admin2",
    categorySlug: "fruits-vegetables",
    createdAt: new Date("2025-06-21")
  },
  {
    title: "Bananas",
    price: 60,
    discountPrice: 50,
    imageUrl: "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcTHACH7SmuUXi8X47amcpcna0CPr1naZL2V5ugcLYtYJJnhmATGJZ91O2_bv-_3svvIP9OApaSM23oXeFwQ0J0VSxkAjqJl",
    quantity: "1 kg",
    sellerName: "Fresh Farms",
    sellerAddress: "1212 Farm Road, Himachal, India",
    manufactureDate: new Date("2025-06-25"),
    expiryDate: new Date("2025-07-10"),
    disclaimer: "Store in a cool, dry place.",
    description: "Sweet and ripe bananas, perfect for snacking.",
    createdBy: "admin3",
    categorySlug: "fruits-vegetables",
    createdAt: new Date("2025-06-22")
  },
  {
    title: "Fresh Spinach",
    price: 40,
    discountPrice: 35,
    imageUrl: "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcQSV3H3Ny8hTuKVdTwpnkk1eOzN5Oa_JjA6gUC0_a6XC1ZsLrtm5WxYSSj075PDfWDSeei5TsSfk5tktF3pKxqEG48F5JA__Y3E2u7oKOOG4iqDLGTkvofVDQ",
    quantity: "500 g",
    sellerName: "Green Fields",
    sellerAddress: "1313 Farm Lane, Punjab, India",
    manufactureDate: new Date("2025-06-27"),
    expiryDate: new Date("2025-07-04"),
    disclaimer: "Refrigerate for freshness.",
    description: "Nutritious fresh spinach for healthy meals.",
    createdBy: "admin4",
    categorySlug: "fruits-vegetables",
    createdAt: new Date("2025-06-23")
  },
  {
    title: "Mangoes",
    price: 150,
    discountPrice: 135,
    imageUrl: "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcSWmgqJf-YkXoqfk3qKgIKtC4NlqI2XuUg23zUuIll_EHNsYAamX45MWtAwfqyTz_jyfw4kyLSW21Xb0BKxokVoxHkTdJSBsmngR_fQyx6eqvN9asWGhADh",
    quantity: "1 kg",
    sellerName: "Fresh Farms",
    sellerAddress: "1212 Farm Road, Himachal, India",
    manufactureDate: new Date("2025-06-26"),
    expiryDate: new Date("2025-07-10"),
    disclaimer: "Store in a cool place.",
    description: "Juicy Alphonso mangoes, king of fruits.",
    createdBy: "admin1",
    categorySlug: "fruits-vegetables",
    createdAt: new Date("2025-06-24")
  },
  {
    title: "Potatoes",
    price: 50,
    discountPrice: 45,
    imageUrl: "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcQ50dcDoBQ5SgYUjC08RVuip06XyFuYfi0sXEO4HkO6_fYBAPR49tEJjWROBcWU0qDfZXSh2cBIk6lf8teyE5wRYGkEjc-g2N1DcqTXjt5qtEsFONhi2pCTSw",
    quantity: "2 kg",
    sellerName: "Green Fields",
    sellerAddress: "1313 Farm Lane, Punjab, India",
    manufactureDate: new Date("2025-06-25"),
    expiryDate: new Date("2025-07-25"),
    disclaimer: "Store in a cool, dry place.",
    description: "Fresh potatoes for versatile cooking.",
    createdBy: "admin2",
    categorySlug: "fruits-vegetables",
    createdAt: new Date("2025-06-25")
  },
  {
    title: "Tomatoes",
    price: 60,
    discountPrice: 50,
    imageUrl: "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcTDWOzxKWPImMg30Dr_N8WyGWrv_s_1ucNd3gjEPr3KfO4ENgqPig_Li3NPjiehFXHdtVcfT-OuOFEwkw_uJahfCSsJDIayXBsHJyhGC4s3sh6BAyUmFfsbQg",
    quantity: "1 kg",
    sellerName: "Green Fields",
    sellerAddress: "1313 Farm Lane, Punjab, India",
    manufactureDate: new Date("2025-06-26"),
    expiryDate: new Date("2025-07-10"),
    disclaimer: "Refrigerate for freshness.",
    description: "Fresh and juicy tomatoes for cooking.",
    createdBy: "admin3",
    categorySlug: "fruits-vegetables",
    createdAt: new Date("2025-06-26")
  },
  
  // 21. Dairy & Bakery
  {
    title: "Toned Milk",
    price: 60,
    discountPrice: 55,
    imageUrl: "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcT52kekiFTwjgm012cbiPCp5ML9DoD7XaAyiu_N3XF9-2pdT0P0JX2-JkgNe-LglzuaJ1Uv8Rn7voKkKpWAwN6wlID-UQWXXfRd8iYLHueWUOE02YS55Hr0hw",
    quantity: "1 litre",
    sellerName: "Pure Dairy",
    sellerAddress: "404 Dairy Road, Gujarat, India",
    manufactureDate: new Date("2025-06-28"),
    expiryDate: new Date("2025-07-05"),
    disclaimer: "Refrigerate after opening.",
    description: "Low-fat toned milk for daily nutrition.",
    createdBy: "admin1",
    categorySlug: "dairy-bakery",
    createdAt: new Date("2025-06-27")
  },
  {
    title: "Salted Butter",
    price: 160,
    discountPrice: 145,
    imageUrl: "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcQiTDLj7PRfagZkE9LRixCiPYZ0nKCqJNe0F3G_vZORwfi1ZHdgealqmmeNG30a_n5w70HyF_QglpatJfhoI0epx9WGn89kFLHv5GX6K-IBRiwBVGO5k1uC",
    quantity: "200 g",
    sellerName: "Pure Dairy",
    sellerAddress: "404 Dairy Road, Gujarat, India",
    manufactureDate: new Date("2025-06-25"),
    expiryDate: new Date("2025-09-25"),
    disclaimer: "Store in a cool place.",
    description: "Creamy salted butter for cooking and spreading.",
    createdBy: "admin2",
    categorySlug: "dairy-bakery",
    createdAt: new Date("2025-06-28")
  },
  {
    title: "Whole Wheat Bread",
    price: 50,
    discountPrice: 45,
    imageUrl: "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcTl2X8u9gBxTtgF5q8rjOzEv_UqIGuHjEGs9LwlcsspTSefPa19Gw1TmKpVM66tB1uPud8risgqeFEUnr_HLm6t4rGYXGyeVwsvDVJzpieLcEdPK1pbTIxc",
    quantity: "400 g",
    sellerName: "Fresh Bakery",
    sellerAddress: "1515 Bakery Lane, Pune, India",
    manufactureDate: new Date("2025-06-27"),
    expiryDate: new Date("2025-07-03"),
    disclaimer: "Contains gluten.",
    description: "Soft whole wheat bread for healthy meals.",
    createdBy: "admin3",
    categorySlug: "dairy-bakery",
    createdAt: new Date("2025-06-29")
  },
  {
    title: "Cheddar Cheese Slices",
    price: 250,
    discountPrice: 225,
    imageUrl: "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcQNzkIx8H7ZsuuGCvLaGO0FDmv3JyGlxHJJZ8Yyw2HVpbtkJVOG5iCiDSlKmCpH-UG8NPSHqhxdUKjILnx57IIXwdfqdCEiIPXEKN2UOKom4wGrJFPdu-u-XQ",
    quantity: "200 g",
    sellerName: "Pure Dairy",
    sellerAddress: "404 Dairy Road, Gujarat, India",
    manufactureDate: new Date("2025-06-26"),
    expiryDate: new Date("2025-09-26"),
    disclaimer: "Refrigerate after opening.",
    description: "Convenient cheddar cheese slices for sandwiches.",
    createdBy: "admin4",
    categorySlug: "dairy-bakery",
    createdAt: new Date("2025-06-30")
  },
  {
    title: "Plain Croissant",
    price: 80,
    discountPrice: 72,
    imageUrl: "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcQcpteifOJcB9iyCcJVDWXHmiTYTHv7H9a3fwpjF5X1pjAfbxRvAlP7ivODXUcrmX2rNeRKMYdSKGGJ0e4qPw-GSK4Pi4C5lYRCCGinurtaYOwfHhWSWNTZ",
    quantity: "2 pieces",
    sellerName: "Fresh Bakery",
    sellerAddress: "1515 Bakery Lane, Pune, India",
    manufactureDate: new Date("2025-06-28"),
    expiryDate: new Date("2025-07-03"),
    disclaimer: "Contains dairy and gluten.",
    description: "Buttery and flaky plain croissants.",
    createdBy: "admin1",
    categorySlug: "dairy-bakery",
    createdAt: new Date("2025-06-27")
  },
  {
    title: "Greek Yogurt",
    price: 100,
    discountPrice: 90,
    imageUrl: "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcR9atUOI4bwOLEufjDuNnDG6kteTellfhtB4sLhjqI7I8btog_q5QlltiTcfkpK_ZygFtfFN1hxQra02LXbY81OJC1OOxS_KQatwES6Zlxx4W3R6tsl_26Q",
    quantity: "200 g",
    sellerName: "Pure Dairy",
    sellerAddress: "404 Dairy Road, Gujarat, India",
    manufactureDate: new Date("2025-06-27"),
    expiryDate: new Date("2025-07-10"),
    disclaimer: "Refrigerate for freshness.",
    description: "Thick and creamy Greek yogurt for healthy snacks.",
    createdBy: "admin2",
    categorySlug: "dairy-bakery",
    createdAt: new Date("2025-06-28")
  },
  {
    title: "Milk Cake",
    price: 300,
    discountPrice: 270,
    imageUrl: "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcSfEx7r7iMZYM9SEiQ-hyNO9HPOZGZ65_zO-XWfvbZ2993R9-FiqfuvaitE5gzGLLcoRcQAiwAvnqAoxPaaSUPdgPUQg6Q9_VlMRyvK7UyJRINXI7wOXtWTpQ",
    quantity: "500 g",
    sellerName: "Fresh Bakery",
    sellerAddress: "1515 Bakery Lane, Pune, India",
    manufactureDate: new Date("2025-06-26"),
    expiryDate: new Date("2025-07-05"),
    disclaimer: "Contains dairy and sugar.",
    description: "Rich and sweet milk cake for dessert.",
    createdBy: "admin3",
    categorySlug: "dairy-bakery",
    createdAt: new Date("2025-06-29")
  },

  // 22. Snacks & Packaged Food
  {
    title: "Masala Cornflakes",
    price: 120,
    discountPrice: 108,
    imageUrl: "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcSvXtuSrbYpRGWZXncC_lsBXjg7cPT9fcj23DXs0-BUfHzvIDEuZNG9HaEbFldzjM5CdeSNYla8zqPE6QEMP8eWPMI69cXBlnBDvxB41BoNvJSNLgDWNDZA",
    quantity: "250 g",
    sellerName: "Snack Zone",
    sellerAddress: "606 Snack Street, Mumbai, India",
    manufactureDate: new Date("2025-06-20"),
    expiryDate: new Date("2025-12-20"),
    disclaimer: "Contains spices.",
    description: "Spicy masala cornflakes for a quick snack.",
    createdBy: "admin1",
    categorySlug: "snacks-packaged-food",
    createdAt: new Date("2025-06-27")
  },
  {
    title: "Instant Noodles",
    price: 50,
    discountPrice: 45,
    imageUrl: "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcStdyWjyh9iwRvT-_wMzMFe-5vvF5-JD-Rn-pGybTtafJnwkPfMmwndXZnFQotbICmTElBHKQibRiy0i1oa7GhqNTN57ofZnot_UzgtW2jQfBquTMUB2ChX",
    quantity: "180 g",
    sellerName: "Snack Zone",
    sellerAddress: "606 Snack Street, Mumbai, India",
    manufactureDate: new Date("2025-06-25"),
    expiryDate: new Date("2026-06-25"),
    disclaimer: "Cook thoroughly before consumption.",
    description: "Quick-cook masala instant noodles.",
    createdBy: "admin2",
    categorySlug: "snacks-packaged-food",
    createdAt: new Date("2025-06-28")
  },
  {
    title: "Cream Biscuits",
    price: 60,
    discountPrice: 54,
    imageUrl: "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcQD6HZ7y-CHEoyFpqE_d-fMt-skDU1riJKcotfxVXDpdqh4u91Nkr_3eMONeBDq6KYppwKb62p1cBNDVElcTfJgX_RgN96i9NByFukTaYnkhb-LFTtK4s2lxdw",
    quantity: "150 g",
    sellerName: "Tasty Treats",
    sellerAddress: "707 Sweet Lane, Delhi, India",
    manufactureDate: new Date("2025-06-20"),
    expiryDate: new Date("2025-12-20"),
    disclaimer: "Contains dairy and gluten.",
    description: "Cream-filled biscuits for tea-time.",
    createdBy: "admin3",
    categorySlug: "snacks-packaged-food",
    createdAt: new Date("2025-06-29")
  },
  {
    title: "Bhujia Sev",
    price: 80,
    discountPrice: 72,
    imageUrl: "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcRrGu6r4khUVrizO2n2H2BToExRSVfmQIzot1YVOgezQxgh00bJqw2Vd1ooAvY1LBfCvXuFJHCgTM0Z7tjJGlbtMyjIyAk9XCbjg41d8fsaWVrQirOJlQArqg",
    quantity: "200 g",
    sellerName: "Snack Zone",
    sellerAddress: "606 Snack Street, Mumbai, India",
    manufactureDate: new Date("2025-06-25"),
    expiryDate: new Date("2025-12-25"),
    disclaimer: "Contains spices and nuts.",
    description: "Crispy and spicy bhujia sev for snacking.",
    createdBy: "admin4",
    categorySlug: "snacks-packaged-food",
    createdAt: new Date("2025-06-30")
  },
  {
    title: "Pasta",
    price: 100,
    discountPrice: 90,
    imageUrl: "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcSi-pC0swosLaxwMwjSAKB-7sLx4dk10SK8-Mu94KynWi0W3JJOST4jNAywuYgSlytPON2xW8Agna8W6oKjy23tuNC1dEdEn-NVCPkLI0kM5_VRwzgZggWn",
    quantity: "500 g",
    sellerName: "Tasty Treats",
    sellerAddress: "707 Sweet Lane, Delhi, India",
    manufactureDate: new Date("2025-06-20"),
    expiryDate: new Date("2026-06-20"),
    disclaimer: "Contains gluten.",
    description: "Durum wheat pasta for quick meals.",
    createdBy: "admin1",
    categorySlug: "snacks-packaged-food",
    createdAt: new Date("2025-06-27")
  },
  {
    title: "Roasted Makhana",
    price: 150,
    discountPrice: 135,
    imageUrl: "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcQZ8OpzWHN5tw8KSlL-IkqVStAtNhnGhlldfskxgqpNcDFYkiFaKoT-pxNxGj04dHNQvdh-SyeSbpluLS_27W1-V2x3ia3BwGbp_c51TFrZJhAday009JQO",
    quantity: "100 g",
    sellerName: "Snack Zone",
    sellerAddress: "606 Snack Street, Mumbai, India",
    manufactureDate: new Date("2025-06-25"),
    expiryDate: new Date("2025-12-25"),
    disclaimer: "Store in an airtight container.",
    description: "Healthy roasted makhana with light spices.",
    createdBy: "admin2",
    categorySlug: "snacks-packaged-food",
    createdAt: new Date("2025-06-28")
  },
  {
    title: "Oat Biscuits",
    price: 70,
    discountPrice: 63,
    imageUrl: "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcTUWVNqLASHEr17cCU4-Nf_Zx5yEYTRlqjKlWrPzIdAYoFZHgEIgfApZpQpIHM9K4FSPJrKQCSU-5JRQqI4Hoqxn0ecuBw82YF9tJCJx2fRm4Ccsj2LAzBq",
    quantity: "200 g",
    sellerName: "Tasty Treats",
    sellerAddress: "707 Sweet Lane, Delhi, India",
    manufactureDate: new Date("2025-06-20"),
    expiryDate: new Date("2025-12-20"),
    disclaimer: "Contains gluten.",
    description: "Crunchy oat biscuits for healthy snacking.",
    createdBy: "admin3",
    categorySlug: "snacks-packaged-food",
    createdAt: new Date("2025-06-29")
  },

  // 23. Mouth Fresheners
  {
    title: "Fennel Seeds (Saunf)",
    price: 80,
    discountPrice: 72,
    imageUrl: "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcR4upBKq8UV3IbBEImm11obn_99TIjfGayQEy0KKpbT5zoKRstK4F7QNsZHfNS77hd58244a6FZy0WvNEw-_n8HfSAAeDeHiGKF0IcAlDsnR-1VNXj0_DtnTA",
    quantity: "100 g",
    sellerName: "Spice Hub",
    sellerAddress: "321 Spice Market, Delhi, India",
    manufactureDate: new Date("2025-06-20"),
    expiryDate: new Date("2026-06-20"),
    disclaimer: "Store in a cool, dry place.",
    description: "Aromatic fennel seeds for fresh breath.",
    createdBy: "admin1",
    categorySlug: "mouth-fresheners",
    createdAt: new Date("2025-06-27")
  },
  {
    title: "Cardamom Pods",
    price: 150,
    discountPrice: 135,
    imageUrl: "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcQBTtW4bgxErfvSJD2V4OqyAR5-IAvGHByd9dhS7-DLixxjlOy-KuUROuNql_WUWuj24cpjIECs4ga5R5Bj_FFSIThQDH6nSfiYEHq8yoePNiQuqak83Xfmgw",
    quantity: "50 g",
    sellerName: "Spice Hub",
    sellerAddress: "321 Spice Market, Delhi, India",
    manufactureDate: new Date("2025-06-25"),
    expiryDate: new Date("2026-06-25"),
    disclaimer: "Store in an airtight container.",
    description: "Premium green cardamom for mouth freshening.",
    createdBy: "admin2",
    categorySlug: "mouth-fresheners",
    createdAt: new Date("2025-06-28")
  },
  {
    title: "Pan Masala",
    price: 100,
    discountPrice: 90,
    imageUrl: "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcQ3m8L72ER3TKlyg0N41ubWxibc2lBDkAgQVqVFsrmmJQx1u0bZDW0yCjiyb7T4z6GCmHdZTcvlBOuNfftFI46NLB9AzQtGOa7ZkKhDuA",
    quantity: "50 g",
    sellerName: "Fresh Bites",
    sellerAddress: "808 Fresh Lane, Mumbai, India",
    manufactureDate: new Date("2025-06-20"),
    expiryDate: new Date("2026-06-20"),
    disclaimer: "Not recommended for children.",
    description: "Traditional pan masala for a refreshing taste.",
    createdBy: "admin3",
    categorySlug: "mouth-fresheners",
    createdAt: new Date("2025-06-29")
  },
  {
    title: "Roasted Betel Nut",
    price: 120,
    discountPrice: 108,
    imageUrl: "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcS6jb2CNGOL9dxurDDi1K4a43Tfd50AXvcWKtXEjMNqIXOIFcYOrhwyMwFAo9MObnyTGGDrRWokVld5sstLBM7LS-KV5DQhFIAyWhksQrE2H2iwhfq83N6NdQ",
    quantity: "100 g",
    sellerName: "Fresh Bites",
    sellerAddress: "808 Fresh Lane, Mumbai, India",
    manufactureDate: new Date("2025-06-25"),
    expiryDate: new Date("2026-06-25"),
    disclaimer: "Consume in moderation.",
    description: "Crunchy roasted betel nut for traditional use.",
    createdBy: "admin4",
    categorySlug: "mouth-fresheners",
    createdAt: new Date("2025-06-30")
  },
  {
    title: "Mint Mukhwas",
    price: 90,
    discountPrice: 81,
    imageUrl: "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcRAGQwAOuNokMpxV2KzZKnlbTatk-S4p1fsKohWDgrCSqqE9QNuKahXCBmVoSzpcpFmqY6keaYIyviXRKHOLvv-eJwQ3ghxzf6E1QnMZSqQ",
    quantity: "100 g",
    sellerName: "Spice Hub",
    sellerAddress: "321 Spice Market, Delhi, India",
    manufactureDate: new Date("2025-06-20"),
    expiryDate: new Date("2026-06-20"),
    disclaimer: "Store in a dry place.",
    description: "Refreshing mint-flavored mukhwas.",
    createdBy: "admin1",
    categorySlug: "mouth-fresheners",
    createdAt: new Date("2025-06-27")
  },
  {
    title: "Sweet Saunf",
    price: 100,
    discountPrice: 90,
    imageUrl: "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcRh50LqUeP_H4WbL2zyrSX3Kx_3XfWVN5piiDiqExZYbuyD5qSqr_QgXOltmoTIjZIX3Gt8m8wQ5vFyDdZswmrtkeVbI1AqYE1HIP_0Z05SvRUnQXMu7_QZ",
    quantity: "100 g",
    sellerName: "Fresh Bites",
    sellerAddress: "808 Fresh Lane, Mumbai, India",
    manufactureDate: new Date("2025-06-25"),
    expiryDate: new Date("2026-06-25"),
    disclaimer: "Contains sugar.",
    description: "Sugar-coated fennel seeds for a sweet aftertaste.",
    createdBy: "admin2",
    categorySlug: "mouth-fresheners",
    createdAt: new Date("2025-06-28")
  },
  {
    title: "Clove Mouth Freshener",
    price: 110,
    discountPrice: 99,
    imageUrl: "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcSF3lYv_wb90O9sfIY6N1l21ZgppT3xVtd-_hvm4CKtzUfoEUPGHFg0lgr6GZKfBvsUcTtgKOWORb96iGhb_AYZPuyrPQioSybVoDXM2w",
    quantity: "50 g",
    sellerName: "Spice Hub",
    sellerAddress: "321 Spice Market, Delhi, India",
    manufactureDate: new Date("2025-06-20"),
    expiryDate: new Date("2026-06-20"),
    disclaimer: "Consume in moderation.",
    description: "Clove-based mouth freshener for strong flavor.",
    createdBy: "admin3",
    categorySlug: "mouth-fresheners",
    createdAt: new Date("2025-06-29")
  },

  // 24. Toffees And Chocolates
  {
    title: "Milk Chocolate Bar",
    price: 100,
    discountPrice: 90,
    imageUrl: "https://www.jiomart.com/images/product/original/491091857/galaxy-silky-smooth-milk-chocolate-bar-20-g-product-images-o491091857-p590110048-0-202403121730.jpg?im=Resize=(420,420)",
    quantity: "50 g",
    sellerName: "Sweet Treats",
    sellerAddress: "707 Sweet Lane, Delhi, India",
    manufactureDate: new Date("2025-06-20"),
    expiryDate: new Date("2025-12-20"),
    disclaimer: "Contains dairy and sugar.",
    description: "Creamy milk chocolate bar for sweet cravings.",
    createdBy: "admin1",
    categorySlug: "toffies-and-chocolates",
    createdAt: new Date("2025-06-27")
  },
  {
    title: "Mango Toffee",
    price: 50,
    discountPrice: 45,
    imageUrl: "https://jammubasket.com/images/products/2373_parle-mango-bite-toffee-60-u-e216af279c7a444e3334ec5561e52fba.jpeg",
    quantity: "100 g",
    sellerName: "Candy Co",
    sellerAddress: "909 Candy Street, Mumbai, India",
    manufactureDate: new Date("2025-06-25"),
    expiryDate: new Date("2026-06-25"),
    disclaimer: "Contains sugar.",
    description: "Tangy mango-flavored toffees.",
    createdBy: "admin2",
    categorySlug: "toffies-and-chocolates",
    createdAt: new Date("2025-06-28")
  },
  {
    title: "Dark Chocolate Bar",
    price: 120,
    discountPrice: 108,
    imageUrl: "https://m.media-amazon.com/images/I/81EAqP0D0+L.jpg",
    quantity: "50 g",
    sellerName: "Sweet Treats",
    sellerAddress: "707 Sweet Lane, Delhi, India",
    manufactureDate: new Date("2025-06-20"),
    expiryDate: new Date("2025-12-20"),
    disclaimer: "Contains cocoa.",
    description: "Rich dark chocolate bar for intense flavor.",
    createdBy: "admin3",
    categorySlug: "toffies-and-chocolates",
    createdAt: new Date("2025-06-29")
  },
  {
    title: "Caramel Candy",
    price: 60,
    discountPrice: 54,
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQH14Ku-rDWa7ZZW8JfHxrckNomZvw1ox_H6A&s",
    quantity: "100 g",
    sellerName: "Candy Co",
    sellerAddress: "909 Candy Street, Mumbai, India",
    manufactureDate: new Date("2025-06-25"),
    expiryDate: new Date("2026-06-25"),
    disclaimer: "Contains dairy and sugar.",
    description: "Chewy caramel candies for a sweet treat.",
    createdBy: "admin4",
    categorySlug: "toffies-and-chocolates",
    createdAt: new Date("2025-06-30")
  },
  {
    title: "Chocolate Truffles",
    price: 300,
    discountPrice: 270,
    imageUrl: "https://www.bbassets.com/media/uploads/p/xxl/40323593_1-amul-truffles.jpg",
    quantity: "200 g",
    sellerName: "Sweet Treats",
    sellerAddress: "707 Sweet Lane, Delhi, India",
    manufactureDate: new Date("2025-06-20"),
    expiryDate: new Date("2025-12-20"),
    disclaimer: "Contains dairy and nuts.",
    description: "Luxurious chocolate truffles for gifting.",
    createdBy: "admin1",
    categorySlug: "toffies-and-chocolates",
    createdAt: new Date("2025-06-27")
  },
  {
    title: "Butterscotch Toffee",
    price: 70,
    discountPrice: 63,
    imageUrl: "https://thumbs.dreamstime.com/b/caramel-golden-butterscotch-toffee-candy-caramels-toffees-copy-space-macro-81548239.jpg",
    quantity: "100 g",
    sellerName: "Candy Co",
    sellerAddress: "909 Candy Street, Mumbai, India",
    manufactureDate: new Date("2025-06-25"),
    expiryDate: new Date("2026-06-25"),
    disclaimer: "Contains dairy and sugar.",
    description: "Rich butterscotch toffees for sweet moments.",
    createdBy: "admin2",
    categorySlug: "toffies-and-chocolates",
    createdAt: new Date("2025-06-28")
  },
  {
    title: "Fruit Jelly Candy",
    price: 80,
    discountPrice: 72,
    imageUrl: "https://images-cdn.ubuy.co.in/633b3c24b66a470ad03bea05-apexy-jelly-fruit-tiktok-candy-trend.jpg",
    quantity: "100 g",
    sellerName: "Candy Co",
    sellerAddress: "909 Candy Street, Mumbai, India",
    manufactureDate: new Date("2025-06-20"),
    expiryDate: new Date("2026-06-20"),
    disclaimer: "Contains sugar.",
    description: "Colorful fruit-flavored jelly candies.",
    createdBy: "admin3",
    categorySlug: "toffies-and-chocolates",
    createdAt: new Date("2025-06-29")
  }

];

module.exports = sampleProducts;